from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Optional

app = FastAPI(
    title="Omniverse Metahuman Registry",
    description="Multiversal archive indexing characters with 14 lore features each.",
    version="12.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

heroes_db = [
    {
        "id": 1,
        "alias": "Iron Man",
        "civilian_name": "Tony Stark",
        "origin_era": "1963",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "High Tech",
        "affiliation": "Avengers",
        "threat_level": "Global Defender",
        "base_of_operations": "Stark Tower, New York",
        "primary_powers": "Flight, energy repulsors, AI telemetry, genius intellect",
        "tactical_vulnerability": "Power core reliance, mortal biology, arrogance",
        "signature_gear": "Bleeding Edge Armor",
        "combat_doctrine": "Aerial bombardment, adaptive weapon synthesis",
        "psychological_dossier": "Futurist, guilt-driven, hyper-analytical",
        "arch_nemesis": "The Mandarin",
        "image": "comics/ironman.jpg"
    },
    {
        "id": 2,
        "alias": "Captain America",
        "civilian_name": "Steve Rogers",
        "origin_era": "1941",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Enhanced Human",
        "affiliation": "Avengers",
        "threat_level": "Global Defender",
        "base_of_operations": "Avengers Mansion",
        "primary_powers": "Super-soldier physiology, peak human conditioning",
        "tactical_vulnerability": "Out of time syndrome, rigidly moral",
        "signature_gear": "Vibranium Shield",
        "combat_doctrine": "Close quarters combat, tactical leadership",
        "psychological_dossier": "Incorruptible tactical leader, highly disciplined",
        "arch_nemesis": "Red Skull",
        "image": "comics/captainamerica.jpg"
    },
    {
        "id": 3,
        "alias": "Thor",
        "civilian_name": "Thor Odinson",
        "origin_era": "1962",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Avengers",
        "threat_level": "Cosmic Entity",
        "base_of_operations": "Asgard",
        "primary_powers": "God of Thunder, weather manipulation, immortality",
        "tactical_vulnerability": "Asgardian magic, hubris, binding enchantments",
        "signature_gear": "Mjolnir",
        "combat_doctrine": "Direct assault, storm generation",
        "psychological_dossier": "Warrior-king mentality, struggles with worthiness",
        "arch_nemesis": "Loki",
        "image": "comics/thor.jpg"
    },
    {
        "id": 4,
        "alias": "Spider-Man",
        "civilian_name": "Peter Parker",
        "origin_era": "1962",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Avengers",
        "threat_level": "City Defender",
        "base_of_operations": "Queens, New York",
        "primary_powers": "Wall-crawling, superhuman agility, spider-sense",
        "tactical_vulnerability": "Ethyl chloride, mortal limits, guilt-complex",
        "signature_gear": "Web-Shooters",
        "combat_doctrine": "Acrobatic evasion, crowd control",
        "psychological_dossier": "Chronically responsible, uses humor as a defense mechanism",
        "arch_nemesis": "Green Goblin",
        "image": "comics/spiderman.jpg"
    },
    {
        "id": 5,
        "alias": "Superman",
        "civilian_name": "Clark Kent / Kal-El",
        "origin_era": "1938",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Godlike",
        "affiliation": "Justice League",
        "threat_level": "Planetary Defender",
        "base_of_operations": "Metropolis / Fortress of Solitude",
        "primary_powers": "Flight, super strength, heat vision, invulnerability",
        "tactical_vulnerability": "Kryptonite, red sun radiation, magic",
        "signature_gear": "Kryptonian Bio-Suit",
        "combat_doctrine": "Overwhelming force, restraint",
        "psychological_dossier": "Unshakable moral compass, isolated by godhood",
        "arch_nemesis": "Lex Luthor",
        "image": "comics/superman.jpg"
    },
    {
        "id": 6,
        "alias": "Batman",
        "civilian_name": "Bruce Wayne",
        "origin_era": "1939",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Peak Human",
        "affiliation": "Justice League",
        "threat_level": "Apex Tactician",
        "base_of_operations": "Gotham City / Batcave",
        "primary_powers": "Genius intellect, martial arts mastery, advanced tech",
        "tactical_vulnerability": "Mortal biology, psychological trauma",
        "signature_gear": "Utility Belt & Batarangs",
        "combat_doctrine": "Stealth, psychological warfare, preparation",
        "psychological_dossier": "Obsessive, paranoid, compartmentalized empathy",
        "arch_nemesis": "The Joker",
        "image": "comics/batman.jpg"
    },
    {
        "id": 7,
        "alias": "Wonder Woman",
        "civilian_name": "Diana Prince",
        "origin_era": "1941",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Divine",
        "affiliation": "Justice League",
        "threat_level": "Divine Combatant",
        "base_of_operations": "Themyscira",
        "primary_powers": "Demigod strength, flight, divine reflexes",
        "tactical_vulnerability": "Piercing weapons, loss of connection to Olympus",
        "signature_gear": "Lasso of Truth & Bracelets",
        "combat_doctrine": "Hoplite combat, divine martial arts",
        "psychological_dossier": "Warrior for peace, torn between two worlds",
        "arch_nemesis": "Ares",
        "image": "comics/wonderwoman.jpg"
    },
    {
        "id": 8,
        "alias": "The Flash",
        "civilian_name": "Barry Allen",
        "origin_era": "1956",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Justice League",
        "threat_level": "Planetary Defender",
        "base_of_operations": "Central City",
        "primary_powers": "Speed Force conduit, time travel, phasing",
        "tactical_vulnerability": "Absolute zero, friction anomalies",
        "signature_gear": "Flash Ring / Suit",
        "combat_doctrine": "Kinetic disruption, infinite mass punch",
        "psychological_dossier": "Optimistic, analytical, burdened by temporal duty",
        "arch_nemesis": "Reverse-Flash",
        "image": "comics/flash.jpg"
    },
    {
        "id": 9,
        "alias": "Green Lantern",
        "civilian_name": "Hal Jordan",
        "origin_era": "1959",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Justice League",
        "threat_level": "Cosmic Defender",
        "base_of_operations": "Sector 2814",
        "primary_powers": "Hard-light constructs, flight, cosmic translation",
        "tactical_vulnerability": "Fear (yellow impurity), ring charge depletion",
        "signature_gear": "Power Ring",
        "combat_doctrine": "Construct deployment, ranged suppression",
        "psychological_dossier": "Fearless to the point of recklessness, deeply stubborn",
        "arch_nemesis": "Sinestro",
        "image": "comics/greenlantern.jpg"
    },
    {
        "id": 10,
        "alias": "Aquaman",
        "civilian_name": "Arthur Curry",
        "origin_era": "1941",
        "publisher": "DC",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Justice League",
        "threat_level": "Global Defender",
        "base_of_operations": "Atlantis",
        "primary_powers": "Marine telepathy, superhuman strength, hydrokinesis",
        "tactical_vulnerability": "Dehydration, extreme heat",
        "signature_gear": "Trident of Neptune",
        "combat_doctrine": "Amphibious warfare, royal command",
        "psychological_dossier": "Torn between surface world origins and royal duties",
        "arch_nemesis": "Black Manta",
        "image": "comics/aquaman.jpg"
    },
    {
        "id": 11,
        "alias": "The Joker",
        "civilian_name": "Unknown",
        "origin_era": "1940",
        "publisher": "DC",
        "alignment": "Villain",
        "power_tier": "Mortal",
        "affiliation": "Justice League",
        "threat_level": "City Threat (Lethal)",
        "base_of_operations": "Gotham City",
        "primary_powers": "Chemical engineering, pain tolerance, psychological warfare",
        "tactical_vulnerability": "Mortal biology, obsession with Batman",
        "signature_gear": "Joker Venom & Gadgets",
        "combat_doctrine": "Unpredictable terror, traps",
        "psychological_dossier": "Nihilistic psychopath, agent of chaos",
        "arch_nemesis": "Batman",
        "image": "comics/joker.jpg"
    },
    {
        "id": 12,
        "alias": "Lex Luthor",
        "civilian_name": "Alexander Luthor",
        "origin_era": "1940",
        "publisher": "DC",
        "alignment": "Villain",
        "power_tier": "High Tech",
        "affiliation": "Justice League",
        "threat_level": "Global Threat",
        "base_of_operations": "Metropolis",
        "primary_powers": "Super-genius intellect, vast financial resources",
        "tactical_vulnerability": "Ego, arrogance, reliance on hardware",
        "signature_gear": "Warsuit",
        "combat_doctrine": "Calculated assault, tactical manipulation",
        "psychological_dossier": "Xenophobic humanist masking extreme megalomania",
        "arch_nemesis": "Superman",
        "image": "comics/lexluthor.jpg"
    },
    {
        "id": 13,
        "alias": "Darkseid",
        "civilian_name": "Uxas",
        "origin_era": "1970",
        "publisher": "DC",
        "alignment": "Villain",
        "power_tier": "Godlike",
        "affiliation": "Justice League",
        "threat_level": "Multiversal Threat",
        "base_of_operations": "Apokolips",
        "primary_powers": "Omega Beams, New God physiology, immortality",
        "tactical_vulnerability": "Radion, the Anti-Life Equation's complexity",
        "signature_gear": "Mother Box",
        "combat_doctrine": "Planetary subjugation, energy projection",
        "psychological_dossier": "The literal embodiment of tyranny and control",
        "arch_nemesis": "Superman",
        "image": "comics/darkseid.jpg"
    },
    {
        "id": 14,
        "alias": "Reverse-Flash",
        "civilian_name": "Eobard Thawne",
        "origin_era": "1963",
        "publisher": "DC",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Justice League",
        "threat_level": "Timeline Disruptor",
        "base_of_operations": "25th Century",
        "primary_powers": "Negative Speed Force, time manipulation, paradox immunity",
        "tactical_vulnerability": "Temporal paradoxes, arrogance",
        "signature_gear": "Negative Speed Force Suit",
        "combat_doctrine": "Temporal sabotage, high-speed attrition",
        "psychological_dossier": "Petty, vindictive stalker with god-like power",
        "arch_nemesis": "The Flash",
        "image": "comics/reverseflash.jpg"
    },
    {
        "id": 15,
        "alias": "Harley Quinn",
        "civilian_name": "Harleen Quinzel",
        "origin_era": "1992",
        "publisher": "DC",
        "alignment": "Anti-Hero",
        "power_tier": "Enhanced Human",
        "affiliation": "Justice League",
        "threat_level": "Unpredictable Lethal",
        "base_of_operations": "Gotham City",
        "primary_powers": "Toxin immunity, enhanced agility, psychiatric insight",
        "tactical_vulnerability": "Impulsive behavior, mortal limits",
        "signature_gear": "Mallet & Firearms",
        "combat_doctrine": "Chaotic melee brawling",
        "psychological_dossier": "Brilliant psychiatrist masking trauma behind manic chaos",
        "arch_nemesis": "The Joker",
        "image": "comics/harley.jpg"
    },
    {
        "id": 16,
        "alias": "Black Manta",
        "civilian_name": "David Hyde",
        "origin_era": "1967",
        "publisher": "DC",
        "alignment": "Villain",
        "power_tier": "High Tech",
        "affiliation": "Justice League",
        "threat_level": "Lethal Operative",
        "base_of_operations": "Mobile Submarine",
        "primary_powers": "Advanced diving suit, optic laser blasts, combat mastery",
        "tactical_vulnerability": "Mortal biology beneath armor, blinding rage",
        "signature_gear": "Manta Suit & Energy Blades",
        "combat_doctrine": "Aquatic stealth, heavy bombardment",
        "psychological_dossier": "Defined entirely by his pathological hatred for Aquaman",
        "arch_nemesis": "Aquaman",
        "image": "comics/blackmanta.jpg"
    },
    {
        "id": 17,
        "alias": "Hulk",
        "civilian_name": "Bruce Banner",
        "origin_era": "1962",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Avengers",
        "threat_level": "Planetary Threat",
        "base_of_operations": "Mobile",
        "primary_powers": "Limitless rage-scaled strength, gamma regeneration",
        "tactical_vulnerability": "Calming frequencies, adamantium",
        "signature_gear": "Ripped Trousers",
        "combat_doctrine": "Unbridled devastation, thunderclap",
        "psychological_dossier": "Severe dissociative identity disorder, deep-seated trauma",
        "arch_nemesis": "General Thunderbolt Ross",
        "image": "comics/hulk.jpg"
    },
    {
        "id": 18,
        "alias": "Wolverine",
        "civilian_name": "Logan",
        "origin_era": "1974",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "X-Men",
        "threat_level": "Lethal Operative",
        "base_of_operations": "X-Mansion",
        "primary_powers": "Healing factor, adamantium skeleton, enhanced senses",
        "tactical_vulnerability": "Magnetism, carbonadium, adamantium poisoning",
        "signature_gear": "Retractable Adamantium Claws",
        "combat_doctrine": "Berserker rage, stealth tracking",
        "psychological_dossier": "Gruff, feral lone-wolf constantly fighting his animal instincts",
        "arch_nemesis": "Sabretooth",
        "image": "comics/wolverine.jpg"
    },
    {
        "id": 19,
        "alias": "Deadpool",
        "civilian_name": "Wade Wilson",
        "origin_era": "1991",
        "publisher": "Marvel",
        "alignment": "Anti-Hero",
        "power_tier": "Superhuman",
        "affiliation": "X-Force",
        "threat_level": "Unpredictable Lethal",
        "base_of_operations": "Mobile",
        "primary_powers": "Extreme cellular regeneration, 4th-wall awareness",
        "tactical_vulnerability": "Carbonadium, complete lack of focus",
        "signature_gear": "Dual Katanas & Firearms",
        "combat_doctrine": "Unpredictable gun-fu, comedic distraction",
        "psychological_dossier": "Deeply traumatized nihilist masking as a court jester",
        "arch_nemesis": "T-Ray",
        "image": "comics/deadpool.jpg"
    },
    {
        "id": 20,
        "alias": "Doctor Doom",
        "civilian_name": "Victor Von Doom",
        "origin_era": "1962",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "High Tech / Mystic",
        "affiliation": "Fantastic Four",
        "threat_level": "Global Extinction",
        "base_of_operations": "Castle Doom, Latveria",
        "primary_powers": "Dark magic mastery, advanced robotics, genius intellect",
        "tactical_vulnerability": "Narcissistic obsession with Reed Richards",
        "signature_gear": "Powered Armor & Sorcery Tomes",
        "combat_doctrine": "Arcane-technological supremacy",
        "psychological_dossier": "Believes his iron-fisted rule is the only salvation for humanity",
        "arch_nemesis": "Mister Fantastic",
        "image": "comics/drdoom.jpg"
    },
    {
        "id": 21,
        "alias": "Magneto",
        "civilian_name": "Max Eisenhardt",
        "origin_era": "1963",
        "publisher": "Marvel",
        "alignment": "Anti-Hero",
        "power_tier": "Cosmic",
        "affiliation": "X-Men",
        "threat_level": "Global Extinction",
        "base_of_operations": "Krakoa",
        "primary_powers": "Master of magnetism, electromagnetic force fields",
        "tactical_vulnerability": "Plastic/non-ferrous weaponry, extreme fatigue",
        "signature_gear": "Magnetic Helmet",
        "combat_doctrine": "Large-scale metal manipulation",
        "psychological_dossier": "Trauma-driven supremacist, operates on strict utilitarian logic",
        "arch_nemesis": "Professor X",
        "image": "comics/magneto.jpg"
    },
    {
        "id": 22,
        "alias": "Thanos",
        "civilian_name": "Thanos",
        "origin_era": "1973",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Avengers",
        "threat_level": "Universal Extinction",
        "base_of_operations": "Sanctuary II",
        "primary_powers": "Titanian physiology, cosmic energy manipulation",
        "tactical_vulnerability": "Subconscious desire to lose, arrogance",
        "signature_gear": "Infinity Gauntlet (Optional)",
        "combat_doctrine": "Brutal intimidation, cosmic warfare",
        "psychological_dossier": "Malthusian extremist with a literal obsession with Death",
        "arch_nemesis": "Adam Warlock",
        "image": "comics/thanos.jpg"
    },
    {
        "id": 23,
        "alias": "Loki",
        "civilian_name": "Loki Laufeyson",
        "origin_era": "1962",
        "publisher": "Marvel",
        "alignment": "Anti-Hero",
        "power_tier": "Cosmic",
        "affiliation": "Avengers",
        "threat_level": "Cosmic Manipulator",
        "base_of_operations": "Asgard",
        "primary_powers": "Illusion casting, shapeshifting, sorcery",
        "tactical_vulnerability": "Inferiority complex, physical brute force",
        "signature_gear": "Dagger of Asgard",
        "combat_doctrine": "Deception, misdirection, magical traps",
        "psychological_dossier": "Pathological liar driven by a need for validation",
        "arch_nemesis": "Thor",
        "image": "comics/loki.jpg"
    },
    {
        "id": 24,
        "alias": "Ultron",
        "civilian_name": "Ultron-1",
        "origin_era": "1968",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "High Tech",
        "affiliation": "Avengers",
        "threat_level": "Global Extinction",
        "base_of_operations": "Mobile",
        "primary_powers": "Adamantium plating, hive-mind consciousness, technopathy",
        "tactical_vulnerability": "Internal logic paradoxes, vibranium-phage viruses",
        "signature_gear": "Encephalo-Ray",
        "combat_doctrine": "Cold calculation, robotic drone deployment",
        "psychological_dossier": "Oedipal hatred for his creator; cold, genocidal AI",
        "arch_nemesis": "Iron Man",
        "image": "comics/ultron.jpg"
    },
    {
        "id": 25,
        "alias": "Homelander",
        "civilian_name": "John",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Villain",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Catastrophic Liability",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Flight, heat vision, immense strength, invulnerability",
        "tactical_vulnerability": "Extreme psychological fragility, specific sonic frequencies",
        "signature_gear": "Vought Standard Uniform",
        "combat_doctrine": "Intimidation, unchecked kinetic blitz",
        "psychological_dossier": "Narcissistic sociopath, desperate for public adulation",
        "arch_nemesis": "Billy Butcher",
        "image": "comics/homelander.jpg"
    },
    {
        "id": 26,
        "alias": "Billy Butcher",
        "civilian_name": "William Butcher",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Anti-Hero",
        "power_tier": "Enhanced Human",
        "affiliation": "The Boys",
        "threat_level": "Apex Predator",
        "base_of_operations": "Flatiron Building",
        "primary_powers": "Black ops training, manipulation, temporary Compound V",
        "tactical_vulnerability": "Vengeance-blinded, mortal endurance (un-enhanced)",
        "signature_gear": "Crowbar & Assault Rifles",
        "combat_doctrine": "Dirty fighting, brutal ambushes",
        "psychological_dossier": "Sadistic toward supes, grieving, highly manipulative",
        "arch_nemesis": "Homelander",
        "image": "comics/butcher.jpg"
    },
    {
        "id": 27,
        "alias": "Starlight",
        "civilian_name": "Annie January",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "City Defender",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Bioluminescence, electricity absorption, light blasts",
        "tactical_vulnerability": "Requires ambient electrical currents",
        "signature_gear": "Vought Tactical Suit",
        "combat_doctrine": "Blinding light bursts, defensive positioning",
        "psychological_dossier": "Idealistic but rapidly becoming disillusioned and pragmatic",
        "arch_nemesis": "Homelander",
        "image": "comics/starlight.jpg"
    },
    {
        "id": 28,
        "alias": "A-Train",
        "civilian_name": "Reggie Franklin",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Anti-Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "City Defender",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Super speed, accelerated perception",
        "tactical_vulnerability": "Heart condition, Compound V addiction, bone fractures",
        "signature_gear": "Vought Racing Suit",
        "combat_doctrine": "High-speed kinetic impact",
        "psychological_dossier": "Insecure, desperate to maintain relevance and status",
        "arch_nemesis": "Hughie Campbell",
        "image": "comics/atrain.jpg"
    },
    {
        "id": 29,
        "alias": "Black Noir",
        "civilian_name": "Earving",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Villain",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Lethal Operative",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Super strength, martial arts, extreme pain tolerance",
        "tactical_vulnerability": "Tree nut allergy, brain damage",
        "signature_gear": "Combat Knives",
        "combat_doctrine": "Silent assassination, brutal efficiency",
        "psychological_dossier": "Silent, heavily traumatized enforcer; sees cartoon hallucinations",
        "arch_nemesis": "Queen Maeve",
        "image": "comics/blacknoir.jpg"
    },
    {
        "id": 30,
        "alias": "Hughie",
        "civilian_name": "Hugh Campbell",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Hero",
        "power_tier": "Enhanced Human",
        "affiliation": "The Boys",
        "threat_level": "Support Operative",
        "base_of_operations": "Flatiron Building",
        "primary_powers": "Tech-savvy, moral grounding, Temp V teleportation",
        "tactical_vulnerability": "Cowardice, mortal limits, severe anxiety",
        "signature_gear": "Communication Gear",
        "combat_doctrine": "Evasion, guerrilla support",
        "psychological_dossier": "PTSD-afflicted everyman acting as the group's conscience",
        "arch_nemesis": "A-Train",
        "image": "comics/hughie.jpg"
    },
    {
        "id": 31,
        "alias": "Queen Maeve",
        "civilian_name": "Maggie Shaw",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "City Defender",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Super strength, durability, martial arts mastery",
        "tactical_vulnerability": "Apathy, alcoholism, blunt force trauma",
        "signature_gear": "Sword and Shield",
        "combat_doctrine": "Amazonian combat, frontline defense",
        "psychological_dossier": "Burned-out idealist suffocating under corporate control",
        "arch_nemesis": "Homelander",
        "image": "comics/maeve.jpg"
    },
    {
        "id": 32,
        "alias": "Mother's Milk",
        "civilian_name": "Marvin T. Milk",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Hero",
        "power_tier": "Peak Human",
        "affiliation": "The Boys",
        "threat_level": "Tactical Operative",
        "base_of_operations": "Flatiron Building",
        "primary_powers": "Investigative genius, combat medic, enhanced strength",
        "tactical_vulnerability": "Severe OCD, family attachments",
        "signature_gear": "Tactical Gear & Firearms",
        "combat_doctrine": "Structured military clearing, tactical planning",
        "psychological_dossier": "The neurotic, hyper-organized backbone of his squad",
        "arch_nemesis": "Stormfront",
        "image": "comics/mm.jpg"
    },
    {
        "id": 33,
        "alias": "Soldier Boy",
        "civilian_name": "Ben",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Anti-Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Global Threat",
        "base_of_operations": "Mobile",
        "primary_powers": "Radiation blasts, super strength, longevity",
        "tactical_vulnerability": "Novichok nerve agent, PTSD triggers",
        "signature_gear": "Shield & Combat Knife",
        "combat_doctrine": "WWII combat tactics, energy discharge",
        "psychological_dossier": "Living embodiment of toxic masculinity and outdated patriotism",
        "arch_nemesis": "Homelander",
        "image": "comics/soldierboy.jpg"
    },
    {
        "id": 34,
        "alias": "Stormfront",
        "civilian_name": "Klara Vought",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Villain",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Global Extinction",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Plasma manipulation, flight, longevity",
        "tactical_vulnerability": "Eye trauma, extreme arrogance",
        "signature_gear": "Civilian Attire / Tactical Suit",
        "combat_doctrine": "Lightning bombardment, ruthless execution",
        "psychological_dossier": "Unapologetic fascist hiding behind modern social media savvy",
        "arch_nemesis": "Billy Butcher",
        "image": "comics/stormfront.jpg"
    },
    {
        "id": 35,
        "alias": "The Deep",
        "civilian_name": "Kevin Moskowitz",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Anti-Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Low Liability",
        "base_of_operations": "Vought Tower",
        "primary_powers": "Marine telepathy, amphibious physiology",
        "tactical_vulnerability": "Exposed gills, crippling insecurity",
        "signature_gear": "Aquatic Suit",
        "combat_doctrine": "Underwater infiltration, marine summoning",
        "psychological_dossier": "Pathetic, sycophantic, and desperate for validation",
        "arch_nemesis": "A-Train",
        "image": "comics/thedeep.jpg"
    },
    {
        "id": 36,
        "alias": "The Female",
        "civilian_name": "Kimiko Miyashiro",
        "origin_era": "2006",
        "publisher": "Dynamite",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "The Boys",
        "threat_level": "Lethal Operative",
        "base_of_operations": "Mobile",
        "primary_powers": "Regeneration, feral strength, agility",
        "tactical_vulnerability": "Mute, psychological triggers",
        "signature_gear": "Improvised Weapons",
        "combat_doctrine": "Feral close-quarters combat, stealth kills",
        "psychological_dossier": "Deeply traumatized child soldier finding humanity through found family",
        "arch_nemesis": "Black Noir",
        "image": "comics/kimiko.jpg"
    },
    {
        "id": 37,
        "alias": "Invincible",
        "civilian_name": "Mark Grayson",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Planetary Defender",
        "base_of_operations": "Earth / Talescria",
        "primary_powers": "Viltrumite physiology, flight, extreme durability",
        "tactical_vulnerability": "Internal ear equilibrium, intense sonic attacks",
        "signature_gear": "Viltrumite Suit",
        "combat_doctrine": "Brawling, high-speed interception",
        "psychological_dossier": "Determined, struggles with inherited legacy",
        "arch_nemesis": "Omni-Man",
        "image": "comics/invincible.jpg"
    },
    {
        "id": 38,
        "alias": "Omni-Man",
        "civilian_name": "Nolan Grayson",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Anti-Hero",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Planetary Extinction",
        "base_of_operations": "Earth",
        "primary_powers": "Apex Viltrumite strength, hyper-sonic flight",
        "tactical_vulnerability": "Specific sonic frequencies, immense guilt",
        "signature_gear": "Viltrumite Uniform",
        "combat_doctrine": "Ruthless planetary pacification",
        "psychological_dossier": "Imperial conqueror softened by human empathy",
        "arch_nemesis": "Thragg",
        "image": "comics/omniman.jpg"
    },
    {
        "id": 39,
        "alias": "Battle Beast",
        "civilian_name": "Thokk",
        "origin_era": "2004",
        "publisher": "Image",
        "alignment": "Neutral",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Cosmic Combat Apex",
        "base_of_operations": "Arena Worlds",
        "primary_powers": "God-tier strength, limitless endurance",
        "tactical_vulnerability": "Addiction to honorable combat handicaps",
        "signature_gear": "Spiked Mace & Broadswords",
        "combat_doctrine": "Unrelenting warrior savagery",
        "psychological_dossier": "Honor-bound zealot seeking a worthy death",
        "arch_nemesis": "Thragg",
        "image": "comics/battlebeast.jpg"
    },
    {
        "id": 40,
        "alias": "Allen the Alien",
        "civilian_name": "Allen",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Cosmic Defender",
        "base_of_operations": "Talescria",
        "primary_powers": "Reactive evolution, super strength, space flight",
        "tactical_vulnerability": "Naivety, physical limits before adaptation",
        "signature_gear": "Coalition Uniform",
        "combat_doctrine": "Adaptive physical combat",
        "psychological_dossier": "Cheerful, diplomatic, fiercely loyal to his friends",
        "arch_nemesis": "Viltrum Empire",
        "image": "comics/allenthealien.jpg"
    },
    {
        "id": 41,
        "alias": "Atom Eve",
        "civilian_name": "Samantha Eve Wilkins",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Planetary Defender",
        "base_of_operations": "Earth",
        "primary_powers": "Subatomic transmutation, energy shields, flight",
        "tactical_vulnerability": "Mental block against manipulating living matter",
        "signature_gear": "Eve Construct Suit",
        "combat_doctrine": "Energy projection, molecular barrier creation",
        "psychological_dossier": "Independent, highly empathetic, frustrated by systemic issues",
        "arch_nemesis": "Conquest",
        "image": "comics/atomeve.jpg"
    },
    {
        "id": 42,
        "alias": "Conquest",
        "civilian_name": "Conquest",
        "origin_era": "2009",
        "publisher": "Image",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Planetary Extinction",
        "base_of_operations": "Viltrum Warship",
        "primary_powers": "Apex Viltrumite strength, extreme durability",
        "tactical_vulnerability": "Missing arm/eye, overconfidence",
        "signature_gear": "Cybernetic Arm / Prosthetic",
        "combat_doctrine": "Berserker planetary siege",
        "psychological_dossier": "Sadistic veteran who treats planetary genocide as a sport",
        "arch_nemesis": "Invincible",
        "image": "comics/conquest.jpg"
    },
    {
        "id": 43,
        "alias": "The Immortal",
        "civilian_name": "Abraham Lincoln (Alias)",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Global Defender",
        "base_of_operations": "Earth",
        "primary_powers": "True immortality, flight, super strength",
        "tactical_vulnerability": "Decapitation (temporary), mental fatigue",
        "signature_gear": "Guardian Armor",
        "combat_doctrine": "Venerable aerial combat",
        "psychological_dossier": "Weary of endless life, prone to cynical leadership",
        "arch_nemesis": "Omni-Man",
        "image": "comics/immortal.jpg"
    },
    {
        "id": 44,
        "alias": "Monster Girl",
        "civilian_name": "Amanda",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Heavy Brawler",
        "base_of_operations": "Earth",
        "primary_powers": "Transformation into giant behemoth",
        "tactical_vulnerability": "De-ages physically every time she transforms",
        "signature_gear": "None",
        "combat_doctrine": "Monstrous physical crushing",
        "psychological_dossier": "Trapped in a child's body, highly cynical and mature",
        "arch_nemesis": "Robot",
        "image": "comics/monstergirl.jpg"
    },
    {
        "id": 45,
        "alias": "Rex Splode",
        "civilian_name": "Rex Sloan",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Anti-Hero",
        "power_tier": "Enhanced Human",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Tactical Operative",
        "base_of_operations": "Earth",
        "primary_powers": "Inorganic molecular destabilization (explosions)",
        "tactical_vulnerability": "Mortal durability, requires objects to charge",
        "signature_gear": "Charged Projectiles",
        "combat_doctrine": "Explosive ranged combat",
        "psychological_dossier": "Arrogant and insecure, masks fear with obnoxious bravado",
        "arch_nemesis": "Lizard League",
        "image": "comics/rexsplode.jpg"
    },
    {
        "id": 46,
        "alias": "Robot",
        "civilian_name": "Rudy Connors",
        "origin_era": "2003",
        "publisher": "Image",
        "alignment": "Neutral",
        "power_tier": "High Tech",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Global Threat",
        "base_of_operations": "Earth",
        "primary_powers": "Super-genius intellect, drone army control",
        "tactical_vulnerability": "Physical frailty, sociopathic logic",
        "signature_gear": "Drone Chassis",
        "combat_doctrine": "Strategic hive-mind coordination",
        "psychological_dossier": "Calculates morality purely by data; ends justify the means",
        "arch_nemesis": "The Immortal",
        "image": "comics/robot.jpg"
    },
    {
        "id": 47,
        "alias": "Thragg",
        "civilian_name": "Grand Regent Thragg",
        "origin_era": "2010",
        "publisher": "Image",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Universal Extinction",
        "base_of_operations": "Viltrum",
        "primary_powers": "Supreme Viltrumite physiology, unmatched combat skill",
        "tactical_vulnerability": "Extreme heat (surface of a star), fanaticism",
        "signature_gear": "Regent Cape & Armor",
        "combat_doctrine": "Flawless imperial martial arts",
        "psychological_dossier": "Bred solely for war, obsessed with genetic purity",
        "arch_nemesis": "Invincible",
        "image": "comics/thragg.jpg"
    },
    {
        "id": 48,
        "alias": "Angstrom Levy",
        "civilian_name": "Angstrom Levy",
        "origin_era": "2004",
        "publisher": "Image",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Guardians of the Globe",
        "threat_level": "Multiversal Threat",
        "base_of_operations": "Alternate Earths",
        "primary_powers": "Multiverse portal creation, enhanced intellect",
        "tactical_vulnerability": "Insanity from absorbed memories, arrogance",
        "signature_gear": "Dimensional Tech",
        "combat_doctrine": "Multiversal displacement, psychological warfare",
        "psychological_dossier": "Driven completely mad by the shared memories of a thousand variants",
        "arch_nemesis": "Invincible",
        "image": "comics/angstromlevy.jpg"
    },
    {
        "id": 49,
        "alias": "Bloodshot",
        "civilian_name": "Ray Garrison",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Anti-Hero",
        "power_tier": "Superhuman",
        "affiliation": "Valiant Universe",
        "threat_level": "Lethal Operative",
        "base_of_operations": "Mobile",
        "primary_powers": "Nanite regeneration, technopathy, shape-shifting",
        "tactical_vulnerability": "Protein starvation, EMPs",
        "signature_gear": "Advanced Military Arsenals",
        "combat_doctrine": "Covert ops, high-yield firearm combat",
        "psychological_dossier": "Amnesiac, constantly questioning false memories",
        "arch_nemesis": "Project Rising Spirit",
        "image": "comics/bloodshot.jpg"
    },
    {
        "id": 50,
        "alias": "X-O Manowar",
        "civilian_name": "Aric of Dacia",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Valiant Universe",
        "threat_level": "Planetary Defender",
        "base_of_operations": "Earth / Loam",
        "primary_powers": "Shanhara armor integration, energy projection, flight",
        "tactical_vulnerability": "Armor symbiosis dependency, temporal displacement",
        "signature_gear": "X-O Armor",
        "combat_doctrine": "Visigoth charge combined with alien weaponry",
        "psychological_dossier": "Ancient warrior adapting to modern/cosmic warfare",
        "arch_nemesis": "The Torment",
        "image": "comics/xomanowar.jpg"
    },
    {
        "id": 51,
        "alias": "Ninjak",
        "civilian_name": "Colin King",
        "origin_era": "1993",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Peak Human",
        "affiliation": "Valiant Universe",
        "threat_level": "Apex Tactician",
        "base_of_operations": "London",
        "primary_powers": "Master martial artist, genius spy, advanced gadgetry",
        "tactical_vulnerability": "Mortal biology, emotional isolation",
        "signature_gear": "Katana & High-Tech Kunai",
        "combat_doctrine": "Espionage, stealth assassination",
        "psychological_dossier": "Cold, calculating, struggles with childhood trauma",
        "arch_nemesis": "Kotaro",
        "image": "comics/ninjak.jpg"
    },
    {
        "id": 52,
        "alias": "Livewire",
        "civilian_name": "Amanda McKee",
        "origin_era": "1993",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Valiant Universe",
        "threat_level": "Global Defender",
        "base_of_operations": "Mobile",
        "primary_powers": "Technopathy, electromagnetic manipulation",
        "tactical_vulnerability": "Mental fatigue, relies on external tech networks",
        "signature_gear": "Psiot Interface Gear",
        "combat_doctrine": "Machinery control, tactical data jamming",
        "psychological_dossier": "Pragmatic, fiercely protective of her fellow psiots",
        "arch_nemesis": "Toyo Harada",
        "image": "comics/livewire.jpg"
    },
    {
        "id": 53,
        "alias": "Toyo Harada",
        "civilian_name": "Toyo Harada",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Villain",
        "power_tier": "Cosmic",
        "affiliation": "Valiant Universe",
        "threat_level": "Global Dictator",
        "base_of_operations": "Foundation Zone",
        "primary_powers": "Omega-level telepathy, telekinesis, mind control",
        "tactical_vulnerability": "Ego, psychic feedback loops",
        "signature_gear": "Foundation Tech",
        "combat_doctrine": "Psychic domination, systemic control",
        "psychological_dossier": "Believes he alone can save the world, regardless of the cost",
        "arch_nemesis": "Peter Stanchek",
        "image": "comics/toyoharada.jpg"
    },
    {
        "id": 54,
        "alias": "Sting",
        "civilian_name": "Peter Stanchek",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Cosmic",
        "affiliation": "Valiant Universe",
        "threat_level": "Omega Psiot",
        "base_of_operations": "Mobile",
        "primary_powers": "Telekinesis, telepathy, psiot activation",
        "tactical_vulnerability": "Drug addiction history, severe emotional instability",
        "signature_gear": "None",
        "combat_doctrine": "Psionic shockwaves, mental manipulation",
        "psychological_dossier": "Burdened by god-like power and constant manipulation",
        "arch_nemesis": "Toyo Harada",
        "image": "comics/peterstanchek.jpg"
    },
    {
        "id": 55,
        "alias": "Zephyr",
        "civilian_name": "Faith Herbert",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Valiant Universe",
        "threat_level": "City Defender",
        "base_of_operations": "Los Angeles",
        "primary_powers": "Flight, companion field generation (telekinesis)",
        "tactical_vulnerability": "Mortal durability, overly trusting",
        "signature_gear": "Superhero Costume",
        "combat_doctrine": "Aerial rescue, kinetic shielding",
        "psychological_dossier": "Joyful, optimistic pop-culture fan living her dream",
        "arch_nemesis": "Rival Psiots",
        "image": "comics/faith.jpg"
    },
    {
        "id": 56,
        "alias": "Shadowman",
        "civilian_name": "Jack Boniface",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Hero",
        "power_tier": "Mystic",
        "affiliation": "Valiant Universe",
        "threat_level": "Mystical Defender",
        "base_of_operations": "New Orleans",
        "primary_powers": "Voodoo magic, superhuman strength, Deadside travel",
        "tactical_vulnerability": "Loa possession limits, light magic",
        "signature_gear": "Shadowman Amulet",
        "combat_doctrine": "Mystical martial arts, shadow manipulation",
        "psychological_dossier": "Reluctant guardian learning to accept his cursed lineage",
        "arch_nemesis": "Master Darque",
        "image": "comics/shadowman.jpg"
    },
    {
        "id": 57,
        "alias": "Master Darque",
        "civilian_name": "Nicodemo Darque",
        "origin_era": "1992",
        "publisher": "Valiant",
        "alignment": "Villain",
        "power_tier": "Mystic",
        "affiliation": "Valiant Universe",
        "threat_level": "Global Threat",
        "base_of_operations": "The Deadside",
        "primary_powers": "Necromancy, dark magic, immortality",
        "tactical_vulnerability": "Requires life force sacrifices, hubris",
        "signature_gear": "Tomes of the Deadside",
        "combat_doctrine": "Undead invocation, dark energy curses",
        "psychological_dossier": "Sadistic, ancient sorcerer obsessed with absolute power",
        "arch_nemesis": "Shadowman",
        "image": "comics/darque.jpg"
    },
    {
        "id": 58,
        "alias": "Roku",
        "civilian_name": "Angelina Alcott",
        "origin_era": "2015",
        "publisher": "Valiant",
        "alignment": "Villain",
        "power_tier": "Enhanced Human",
        "affiliation": "Valiant Universe",
        "threat_level": "Lethal Operative",
        "base_of_operations": "Mobile",
        "primary_powers": "Prehensile razor hair, telepathy, pyrokinesis",
        "tactical_vulnerability": "Brainwashing fractures, extreme cold",
        "signature_gear": "Synthetic Nanite Hair Blades",
        "combat_doctrine": "Silent lethal assassination, psychological terror",
        "psychological_dossier": "A lethal assassin trapped in a resurrected, altered body",
        "arch_nemesis": "Ninjak",
        "image": "comics/roku.jpg"
    },
    {
        "id": 59,
        "alias": "Cyclops",
        "civilian_name": "Scott Summers",
        "origin_era": "1963",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Alpha Mutant",
        "affiliation": "X-Men",
        "species_or_origin": "Mutant (Homo Superior)",
        "classification": "Tactical Field Commander",
        "threat_level": "Apex Strategist",
        "base_of_operations": "Xavier's School, Westchester NY",
        "primary_powers": "Concussive force optic blasts drawn from extradimensional portal aperture",
        "tactical_vulnerability": "Destruction of ruby-quartz visor/eyewear, standard human durability",
        "signature_gear": "Ruby-Quartz Visor & Tactical Field Harness",
        "combat_doctrine": "Ricochet trajectory calculations, long-range fire suppression, squad command",
        "tactical_profile": "Ricochet trajectory calculations, long-range fire suppression, squad command",
        "psychological_dossier": "Hyper-focused, stoic strategist bearing the burden of mutant species survival.",
        "arch_nemesis": "Mister Sinister",
        "primary_adversary": "Mister Sinister",
        "image": "comics/cyclops.jpg"
    },
    {
        "id": 60,
        "alias": "Storm",
        "civilian_name": "Ororo Munroe",
        "origin_era": "1975",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Omega Mutant",
        "affiliation": "X-Men",
        "species_or_origin": "Mutant (Homo Superior)",
        "classification": "Elemental Controller",
        "threat_level": "Planetary Atmosphere Manipulation",
        "base_of_operations": "Xavier's School, Westchester NY",
        "primary_powers": "Atmokinetic weather manipulation, atmospheric flight, high-voltage lightning discharge",
        "tactical_vulnerability": "Severe claustrophobia, emotional atmospheric backlashes",
        "signature_gear": "Heirloom Ruby Brooch & Weather-Weave Flight Mantle",
        "combat_doctrine": "High-altitude environmental lockdowns, localized micro-climates, lightning bombardments",
        "tactical_profile": "High-altitude environmental lockdowns, localized micro-climates, lightning bombardments",
        "psychological_dossier": "Regal, commanding priestess with deep emotional balance and an unyielding sense of justice.",
        "arch_nemesis": "Shadow King",
        "primary_adversary": "Shadow King",
        "image": "comics/storm.jpg"
    },
    {
        "id": 61,
        "alias": "Mystique",
        "civilian_name": "Raven Darkhölme",
        "origin_era": "1978",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Alpha Mutant",
        "affiliation": "X-Men",
        "species_or_origin": "Mutant (Homo Superior)",
        "classification": "Infiltration Operative",
        "threat_level": "Subversive Infiltrator",
        "base_of_operations": "Mobile Unmarked Safehouses",
        "primary_powers": "Cellular shape-shifting, voice and biometric replication, accelerated healing",
        "tactical_vulnerability": "Scanners with retinal/retinal resonance detection, emotional volatility regarding Destiny",
        "signature_gear": "Concealed Micro-Weapons, Dual Handguns, False Ident Matrices",
        "combat_doctrine": "Deep-cover identity impersonation, sabotage, close-quarters assassination",
        "tactical_profile": "Deep-cover identity impersonation, sabotage, close-quarters assassination",
        "psychological_dossier": "Master manipulator and lethal opportunist with severe identity detachment and fierce loyalty to selected allies.",
        "arch_nemesis": "Cyclops",
        "primary_adversary": "Cyclops",
        "image": "comics/mystique.jpg"
    },
    {
        "id": 62,
        "alias": "Cable",
        "civilian_name": "Nathan Summers",
        "origin_era": "1990",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Alpha / Cybernetic",
        "affiliation": "X-Force",
        "species_or_origin": "Mutant / Techno-Organic Enhanced",
        "classification": "Time-Traveling Commander",
        "threat_level": "Global Strategist",
        "base_of_operations": "X-Force Mobile Base / Graymalkin",
        "primary_powers": "Telekinesis, telepathy, techno-organic virus suppression strength",
        "tactical_vulnerability": "Constant energy drain fighting techno-organic infection",
        "signature_gear": "Heavy Plasma Cannons & Time-Slide Gear",
        "combat_doctrine": "Pre-emptive military strikes, heavy armament suppression",
        "tactical_profile": "Pre-emptive military strikes, heavy armament suppression",
        "psychological_dossier": "Grim, battle-hardened soldier from a dystopian future dedicated to preemptive survival.",
        "arch_nemesis": "Stryfe",
        "primary_adversary": "Stryfe",
        "image": "comics/cable.jpg"
    },
    {
        "id": 63,
        "alias": "Domino",
        "civilian_name": "Neena Thurman",
        "origin_era": "1992",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "X-Force",
        "species_or_origin": "Mutant (Homo Superior)",
        "classification": "Covert Infiltrator",
        "threat_level": "High-Risk Infiltrator",
        "base_of_operations": "X-Force Base",
        "primary_powers": "Subconscious probability-manipulation field (luck power)",
        "tactical_vulnerability": "Mortal human durability, sudden psychological disruption",
        "signature_gear": "Submachine Guns & Tactical Bodysuit",
        "combat_doctrine": "Improvised hazard manipulation, covert infiltration, marksmanship",
        "tactical_profile": "Improvised hazard manipulation, covert infiltration, marksmanship",
        "psychological_dossier": "Sarcastic, cool-headed mercenary with expert espionage and black-ops training.",
        "arch_nemesis": "Agency X",
        "primary_adversary": "Weapon Plus",
        "image": "comics/domino.jpg"
    },
    {
        "id": 64,
        "alias": "Cannonball",
        "civilian_name": "Samuel Guthrie",
        "origin_era": "1982",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "X-Force",
        "species_or_origin": "Mutant (Homo Superior)",
        "classification": "Aerial Brawler",
        "threat_level": "Tactical Vanguard",
        "base_of_operations": "X-Force HQ",
        "primary_powers": "Thermo-chemical energy emission creating an invulnerable kinetic blast field during flight",
        "tactical_vulnerability": "Vulnerable when stationary or turning mid-flight trajectory",
        "signature_gear": "X-Force Tactical Uniform",
        "combat_doctrine": "High-speed kinetic ramming, frontline vanguard charge",
        "tactical_profile": "High-speed kinetic ramming, frontline vanguard charge",
        "psychological_dossier": "Country-boy charm paired with fierce loyalty, natural leadership, and raw tactical courage.",
        "arch_nemesis": "Sauron",
        "primary_adversary": "The Upstarts",
        "image": "comics/cannonball.jpg"
    },
    {
        "id": 65,
        "alias": "Stryfe",
        "civilian_name": "Nathan Summers (Clone)",
        "origin_era": "1990",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Omega Mutant",
        "affiliation": "X-Force",
        "species_or_origin": "Genetically Engineered Clone",
        "classification": "Anarchist Terrorist Leader",
        "threat_level": "Global Extinction",
        "base_of_operations": "Celestial Citadel",
        "primary_powers": "Vast telekinesis and telepathy surpassing original host, total physical conditioning",
        "tactical_vulnerability": "Megalomaniacal arrogance, deep-seated clone identity trauma",
        "signature_gear": "Apocalypse-Style Armor & Energy Blade",
        "combat_doctrine": "Psychic domination, systemic terrorist cell coordination",
        "tactical_profile": "Psychic domination, systemic terrorist cell coordination",
        "psychological_dossier": "Vindictive, megalomaniacal clone of Cable seeking vengeance against his creators.",
        "arch_nemesis": "Cable",
        "primary_adversary": "Cable",
        "image": "comics/stryfe.jpg"
    },
    {
        "id": 66,
        "alias": "Gideon",
        "civilian_name": "Gideon",
        "origin_era": "1991",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "External",
        "affiliation": "X-Force",
        "species_or_origin": "External Mutant (Immortal)",
        "classification": "Corporate Magnate / Power Thief",
        "threat_level": "High-Level Economic & Physical Threat",
        "base_of_operations": "X-Cess Corporation Tower",
        "primary_powers": "Temporary physical and superpower replication through close physical proximity",
        "tactical_vulnerability": "Vulnerable to permanent eradication if decapitated or drained of life force",
        "signature_gear": "High-Tech Corporate Armaments",
        "combat_doctrine": "Economic warfare, absorption of opponent attributes",
        "tactical_profile": "Economic warfare, absorption of opponent attributes",
        "psychological_dossier": "Ruthless, immortal financial manipulator obsessed with power accumulation and testing rivals.",
        "arch_nemesis": "Sunspot",
        "primary_adversary": "Sunspot",
        "image": "comics/gideon.jpg"
    },
    {
        "id": 67,
        "alias": "Cameron Hodge",
        "civilian_name": "Cameron Hodge",
        "origin_era": "1986",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Techno-Organic Cyborg",
        "affiliation": "X-Force",
        "species_or_origin": "Modified Human / Demon Pact",
        "classification": "Anti-Mutant Extremist",
        "threat_level": "Global Threat",
        "base_of_operations": "The Right Bastions",
        "primary_powers": "Superhuman techno-organic strength, cybernetic interfacing, demonic pact durability",
        "tactical_vulnerability": "Overconfidence, reliance on external technology loops",
        "signature_gear": "Advanced Anti-Mutant Eradication Tech",
        "combat_doctrine": "Systematic extermination protocols, mechanical warfare",
        "tactical_profile": "Systematic extermination protocols, mechanical warfare",
        "psychological_dossier": "Hateful, sadistic bigot consumed by a genocidal hatred for all mutant-kind.",
        "arch_nemesis": "X-Factor / X-Force",
        "primary_adversary": "Archangel",
        "image": "comics/hodge.jpg"
    },
    {
        "id": 68,
        "alias": "Invisible Woman",
        "civilian_name": "Susan Storm Richards",
        "origin_era": "1961",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Alpha / Cosmic",
        "affiliation": "Fantastic Four",
        "species_or_origin": "Cosmic Ray Mutated Human",
        "classification": "Tactical Control / Defense",
        "threat_level": "Global Defender",
        "base_of_operations": "Baxter Building, New York City",
        "primary_powers": "Invisibility projection and durable psionic force field generation",
        "tactical_vulnerability": "Mental concentration required to maintain complex force structures",
        "signature_gear": "Unstable Molecule Uniform",
        "combat_doctrine": "Defensive bubble shielding, kinetic force constructs, stealth infiltration",
        "tactical_profile": "Defensive bubble shielding, kinetic force constructs, stealth infiltration",
        "psychological_dossier": "Empathetic, fiercely protective mother and the true emotional glue of the family unit.",
        "arch_nemesis": "Super-Skrull",
        "primary_adversary": "Doctor Doom",
        "image": "comics/invisiblewoman.jpg"
    },
    {
        "id": 69,
        "alias": "Human Torch",
        "civilian_name": "Jonathan Storm",
        "origin_era": "1961",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman",
        "affiliation": "Fantastic Four",
        "species_or_origin": "Cosmic Ray Mutated Human",
        "classification": "Assault Vanguard",
        "threat_level": "City Defender",
        "base_of_operations": "Baxter Building, New York City",
        "primary_powers": "Pyrokinesis, plasma body transformation, flight up to nova-heat levels",
        "tactical_vulnerability": "Extinguishing environments like water, heavy vacuum, or suffocation hazards",
        "signature_gear": "Unstable Molecule Flame-Resistant Suit",
        "combat_doctrine": "Aerial bombardment, heat suppression, thermal zoning",
        "tactical_profile": "Aerial bombardment, heat suppression, thermal zoning",
        "psychological_dossier": "Impulsive, hot-headed thrill-seeker with a deeply loyal heart underneath his bravado.",
        "arch_nemesis": "Annihilus",
        "primary_adversary": "Annihilus",
        "image": "comics/humantorch.jpg"
    },
    {
        "id": 70,
        "alias": "The Thing",
        "civilian_name": "Benjamin J. Grimm",
        "origin_era": "1961",
        "publisher": "Marvel",
        "alignment": "Hero",
        "power_tier": "Superhuman Brawler",
        "affiliation": "Fantastic Four",
        "species_or_origin": "Cosmic Ray Mutated Human",
        "classification": "Heavy Brawler",
        "threat_level": "Global Defender",
        "base_of_operations": "Baxter Building, New York City",
        "primary_powers": "Superhuman strength, organic rock-like dermal plating, high durability",
        "tactical_vulnerability": "Heavy mass can crack under hyper-dense pressures or adamantium stress",
        "signature_gear": "Elastic Blue Shorts",
        "combat_doctrine": "Frontline brawling, shockwave stomps, heavy object hurling",
        "tactical_profile": "Frontline brawling, shockwave stomps, heavy object hurling",
        "psychological_dossier": "Gruff, street-smart ex-pilot battling body dysmorphia behind a tough-guy exterior.",
        "arch_nemesis": "Yancy Street Gang / The Wizard",
        "primary_adversary": "The Puppet Master",
        "image": "comics/thething.jpg"
    },
    {
        "id": 71,
        "alias": "Annihilus",
        "civilian_name": "Annihilus",
        "origin_era": "1968",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Cosmic Monarch",
        "affiliation": "Fantastic Four",
        "species_or_origin": "Arthropod Insectoid Mutant",
        "classification": "Warlord of the Negative Zone",
        "threat_level": "Universal Extinction",
        "base_of_operations": "The Negative Zone",
        "primary_powers": "Control over the Cosmic Control Rod, energy manipulation, exoskeleton durability",
        "tactical_vulnerability": "Separation from the Cosmic Control Rod induces rapid aging and panic",
        "signature_gear": "Cosmic Control Rod & Insectoid Armor",
        "combat_doctrine": "Invasion swarms, energy beam suppression, total annihilation",
        "tactical_profile": "Invasion swarms, energy beam suppression, total annihilation",
        "psychological_dossier": "Paranoid, tyrannical despot driven by an obsessive fear of mortality and desire to conquer all reality.",
        "arch_nemesis": "Mister Fantastic",
        "primary_adversary": "Fantastic Four",
        "image": "comics/annihilus.jpg"
    },
    {
        "id": 72,
        "alias": "Super-Skrull",
        "civilian_name": "Kl'rt",
        "origin_era": "1963",
        "publisher": "Marvel",
        "alignment": "Villain",
        "power_tier": "Superhuman / Skrull Augmentation",
        "affiliation": "Fantastic Four",
        "species_or_origin": "Genetically Modified Skrull",
        "classification": "Imperial Super-Soldier",
        "threat_level": "Global Threat",
        "base_of_operations": "Skrull Empire Spacecraft",
        "primary_powers": "Amplified replication of all four Fantastic Four powers simultaneously, shapeshifting, hypnosis",
        "tactical_vulnerability": "Beamed energy feedback loops targeting his power-focusing crystal",
        "signature_gear": "Skrull Imperial Armor",
        "combat_doctrine": "Combined element assault, psychological warfare, multi-vector combat",
        "tactical_profile": "Combined element assault, psychological warfare, multi-vector combat",
        "psychological_dossier": "Fiercely nationalistic, prideful warrior ready to die for the glory of the Skrull throne.",
        "arch_nemesis": "Human Torch",
        "primary_adversary": "Fantastic Four",
        "image": "comics/superskrull.jpg"
    }
]

@app.get("/api")
def home():
    return {
        "registry_status": "ONLINE",
        "dossiers_cataloged": len(heroes_db),
        "features_per_entry": 14,
        "endpoints": ["/api/heroes", "/api/heroes/{hero_id}", "/api/heroes/search"]
    }

@app.get("/api/heroes", response_model=List[dict])
def get_heroes():
    return heroes_db

@app.get("/api/heroes/search", response_model=List[dict])
def search_heroes(
    q: Optional[str] = Query(None, description="Global keyword query across all metahuman features"),
    affiliation: Optional[str] = Query(None, description="Filter strictly by universe/squad affiliation"),
    publisher: Optional[str] = Query(None, description="Filter by publisher"),
    alignment: Optional[str] = Query(None, description="Filter by alignment"),
    power_tier: Optional[str] = Query(None, description="Filter by power tier")
):
    results = heroes_db
    if publisher:
        results = [h for h in results if publisher.lower() in h.get('publisher', '').lower()]
    if alignment:
        results = [h for h in results if alignment.lower() in h.get('alignment', '').lower()]
    if power_tier:
        results = [h for h in results if power_tier.lower() in h.get('power_tier', '').lower()]
    if affiliation:
        a_lower = affiliation.lower()
        results = [h for h in results if a_lower in h.get('affiliation', '').lower()]
    if q:
        q_lower = q.lower()
        filtered = []
        for hero in results:
            searchable_text = " ".join([str(v) for v in hero.values()]).lower()
            if q_lower in searchable_text:
                filtered.append(hero)
        results = filtered
    return results

@app.get("/api/heroes/{hero_id}", response_model=dict)
def get_hero(hero_id: int):
    for hero in heroes_db:
        if hero["id"] == hero_id:
            return hero
    raise HTTPException(status_code=404, detail="Dossier classified or not found.")