from fastapi import FastAPI, HTTPException, Query
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Optional

app = FastAPI(
    title="Omniverse Metahuman Registry",
    description="Classified dossier registry documenting superhuman entities, cosmic artifacts, and kinetic metahumans.",
    version="4.0.0"
)

app.mount("/comics", StaticFiles(directory="comics"), name="comics")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

heroes_db = [
    {
        "id": 1,
        "alias": "Iron Man",
        "civilian_name": "Tony Stark",
        "origin_era": 1963,
        "classification": "Technological Singularity / Powered Exoskeleton",
        "threat_level": "Global Technological Hegemony",
        "affiliation": "Avengers / Stark Industries",
        "base_of_operations": "New York City / Stark Tower",
        "primary_powers": "Hyper-polymath engineering intellect, zero-point energy manipulation, real-time AI tactical telemetry",
        "tactical_vulnerability": "Power core dependency, biological human frailty outside armor",
        "signature_gear": "Bleeding Edge Modular Armor, Repulsor Core Cannons, F.R.I.D.A.Y. AI Interface",
        "tactical_profile": "Orbital laser bombardment, supersonic strafing runs, adaptive weapon synthesis",
        "psychological_dossier": "Futurist visionary, guilt-driven, hyper-analytical, control-oriented",
        "image": "comics/ironman.jpg"
    },
    {
        "id": 2,
        "alias": "Captain America",
        "civilian_name": "Steve Rogers",
        "origin_era": 1941,
        "classification": "Super-Soldier Serum Peak Human",
        "threat_level": "Global Field Commander / Tactical Apex",
        "affiliation": "Avengers / S.H.I.E.L.D.",
        "base_of_operations": "Brooklyn, New York City",
        "primary_powers": "Peak physical conditioning, master hand-to-hand combatant, field tactician, accelerated metabolic recovery",
        "tactical_vulnerability": "Mortal biological constraints, strict adherence to democratic moral ideals",
        "signature_gear": "Vibranium-Steel Concave Shield, Reinforced Scale-Mail Armor",
        "tactical_profile": "Ricochet shield trajectories, defensive phalanx blocking, fluid martial arts integration",
        "psychological_dossier": "Incorruptible moral compass, natural battlefield leader, unwavering defender of liberty",
        "image": "comics/captainamerica.jpg"
    },
    {
        "id": 3,
        "alias": "Thor",
        "civilian_name": "Thor Odinson",
        "origin_era": 1962,
        "classification": "Asgardian Cosmic Deity",
        "threat_level": "Planetary / Godhead Annihilator",
        "affiliation": "Avengers / Asgard Realm",
        "base_of_operations": "Asgard / Midgard",
        "primary_powers": "Electrokinesis, weather manipulation, godlike physiology, longevity, dimensional rift generation",
        "tactical_vulnerability": "Warrior's Madness hubris, dependence on divine focus weapons",
        "signature_gear": "Mjölnir (Uru Hammer), Stormbreaker Axe, Megingjörð Belt of Strength",
        "tactical_profile": "Tectonic lightning strikes, close-quarters blunt trauma, atmospheric upheaval",
        "psychological_dossier": "Noble, battle-hungry, honorable, burdened by divine royal duty",
        "image": "comics/thor.jpg"
    },
    {
        "id": 4,
        "alias": "Hulk",
        "civilian_name": "Bruce Banner",
        "origin_era": 1962,
        "classification": "Gamma Mutation Kinetic Behemoth",
        "threat_level": "World-Breaker Class / Uncapped Kinetic Scale",
        "affiliation": "Avengers / Defenders",
        "base_of_operations": "New Mexico Desert / Subterranean Lab",
        "primary_powers": "Uncapped strength scaling with rage, hyper-regenerative healing, absolute kinetic resistance",
        "tactical_vulnerability": "Calming neuro-chemical agents, antimatter siphon rays, psychic soothing",
        "signature_gear": "Indestructible Micro-Polymer Pants",
        "tactical_profile": "Unrestrained ground-pounding, thunderclaps, seismic demolition",
        "psychological_dossier": "Dual-personality war, primal defensive id vs. suicidal genius ego",
        "image": "comics/hulk.jpg"
    },
    {
        "id": 5,
        "alias": "Spider-Man",
        "civilian_name": "Peter Parker",
        "origin_era": 1962,
        "classification": "Mutated Arachnid Conduit",
        "threat_level": "Urban Protector / High Metahuman Potential",
        "affiliation": "Avengers / Street-Level Resistance",
        "base_of_operations": "Queens, New York City",
        "primary_powers": "Precognitive spider-sense, wall-crawling, superhuman agility/reflexes, proportional strength",
        "tactical_vulnerability": "Ethyl chloride pesticide analogs, psychological guilt, fragile unarmored anatomy",
        "signature_gear": "Fluid Web-Shooters, Spider-Tracers, Stark Nanotech Weave",
        "tactical_profile": "Acrobatic dynamic redirection, environmental tethering, improvisational physics",
        "psychological_dossier": "Pathologically responsible, self-sacrificing, quick-witted, relentless",
        "image": "comics/spiderman.jpg"
    },
    {
        "id": 6,
        "alias": "Doctor Strange",
        "civilian_name": "Stephen Strange",
        "origin_era": 1963,
        "classification": "Mystic Conduit / Astral Architect",
        "threat_level": "Dimensional / Reality-Altering",
        "affiliation": "Masters of the Mystic Arts / Avengers",
        "base_of_operations": "New York / Sanctum Sanctorum",
        "primary_powers": "Reality manipulation, dimensional travel, chronokinesis, astral projection, eldritch spells",
        "tactical_vulnerability": "Incantation requirement, physical somatic gestures, mystical backlash",
        "signature_gear": "Eye of Agamotto (Time Artifact), Cloak of Levitation, Book of the Vishanti",
        "tactical_profile": "Inter-dimensional displacement, temporal recursion, esoteric energy barriers",
        "psychological_dossier": "Pragmatic, detached, burdened by multiversal foresight, cerebral",
        "image": "comics/drstrange.jpg"
    },
    {
        "id": 7,
        "alias": "Scarlet Witch",
        "civilian_name": "Wanda Maximoff",
        "origin_era": 1964,
        "classification": "Chaos Magic Nexus Entity",
        "threat_level": "Omega-Level / Reality-Collapsing",
        "affiliation": "Avengers / Independent Nexus",
        "base_of_operations": "Wundagore Mountain / Transia",
        "primary_powers": "Spontaneous probability alteration, Chaos Magic casting, matter transmutation, telekinesis",
        "tactical_vulnerability": "Emotional instability, mental fractures, extreme psionic feedback",
        "signature_gear": "Darkhold Codex, Chaos Channeling Focus",
        "tactical_profile": "Widespread reality reconstruction, matter unraveling, mental subjugation",
        "psychological_dossier": "Grief-shattered, volatile, intensely protective, morally ambiguous",
        "image": "comics/scarletwitch.jpg"
    },
    {
        "id": 8,
        "alias": "Black Panther",
        "civilian_name": "T'Challa",
        "origin_era": 1966,
        "classification": "Vibranium-Enhanced Warrior King",
        "threat_level": "Global Strategic Monarch",
        "affiliation": "Avengers / Kingdom of Wakanda",
        "base_of_operations": "Birnin Zana, Wakanda",
        "primary_powers": "Heart-Shaped Herb physical enhancements, tactical genius, King of the Dead necromancy",
        "tactical_vulnerability": "Anti-metal sonic harmonics, vibranium breakdown waves",
        "signature_gear": "Microweave Vibranium Habit, Energy Daggers, Kimoyo Bead Array",
        "tactical_profile": "Silent martial takedowns, kinetic energy absorption and discharge counter-attacks",
        "psychological_dossier": "Stoic sovereign, ruthlessly pragmatic leader, spiritually bound ancestor guardian",
        "image": "comics/blackpanther.jpg"
    },
    {
        "id": 9,
        "alias": "Captain Marvel",
        "civilian_name": "Carol Danvers",
        "origin_era": 1968,
        "classification": "Kree-Human Cosmic Hybrid",
        "threat_level": "Planetary Annihilator / Interstellar Vanguard",
        "affiliation": "Avengers / Alpha Flight Space Program",
        "base_of_operations": "Low Earth Orbit / Alpha Flight Station",
        "primary_powers": "Cosmic photonic energy projection, binary mode stellar transformation, super-luminal flight",
        "tactical_vulnerability": "Energy saturation limits, vulnerability to psionic power siphoning",
        "signature_gear": "Kree Battle Suit with Retractable Flight Helmet",
        "tactical_profile": "Supersonic strafing runs, concentrated photon beam bombardments, close-quarters grappling",
        "psychological_dossier": "Fiercely independent, decisive military tactician, aggressive defender",
        "image": "comics/captainmarvel.jpg"
    },
    {
        "id": 10,
        "alias": "Daredevil",
        "civilian_name": "Matt Murdock",
        "origin_era": 1964,
        "classification": "Radar-Sense Acoustic Metahuman",
        "threat_level": "Street-Level Urban Enforcer",
        "affiliation": "Defenders / Nelson & Murdock",
        "base_of_operations": "Hell's Kitchen, New York City",
        "primary_powers": "360-degree radar sense, superhuman tactile/acoustic perception, master martial artist",
        "tactical_vulnerability": "High-decibel acoustic overload, localized olfactory toxins",
        "signature_gear": "Multipurpose Billy Club / Grappling Tether, Devil Cowl Suit",
        "tactical_profile": "Ricochet trajectory strikes, parkour evasion, pressure-point brawling",
        "psychological_dossier": "Guilt-ridden Catholic vigilante, righteous, masochistic, relentless",
        "image": "comics/daredevil.jpg"
    },
    {
        "id": 11,
        "alias": "Batman",
        "civilian_name": "Bruce Wayne",
        "origin_era": 1939,
        "classification": "Peak Human / Strategic Tactician",
        "threat_level": "Global Strategic Threat (Contingency Master)",
        "affiliation": "Justice League / Bat-Family",
        "base_of_operations": "Gotham City / The Batcave",
        "primary_powers": "Genius intellect, master martial artist, forensic science, psychological warfare",
        "tactical_vulnerability": "Standard human physical limits, unyielding psychological trauma",
        "signature_gear": "Reinforced Kevlar Cowl, Grapple Gun, Batarangs, Heavy Batmobile",
        "tactical_profile": "Stealth ambush, environmental weaponization, pressure-point neutralization",
        "psychological_dossier": "Obsessive, austere, fiercely disciplined, relentless moral code",
        "image": "comics/batman.jpg"
    },
    {
        "id": 12,
        "alias": "Superman",
        "civilian_name": "Clark Kent / Kal-El",
        "origin_era": 1938,
        "classification": "Kryptonian Solar-Battery Metahuman",
        "threat_level": "Extinction-Level / Planetary Safeguard",
        "affiliation": "Justice League",
        "base_of_operations": "Metropolis / Fortress of Solitude",
        "primary_powers": "Superhuman strength, invulnerability, light-speed flight, heat vision, freeze breath",
        "tactical_vulnerability": "Kryptonite radiation, red solar radiation, psionic and magic attacks",
        "signature_gear": "Indestructible Kryptonian Bio-Suit, Phantom Zone Projector",
        "tactical_profile": "Direct kinetic confrontation, aerial dominance, catastrophic damage containment",
        "psychological_dossier": "Altruistic, compassionate, unwavering moral beacon, self-restrained",
        "image": "comics/superman.jpg"
    },
    {
        "id": 13,
        "alias": "Wonder Woman",
        "civilian_name": "Diana Prince",
        "origin_era": 1941,
        "classification": "Divine Amazonian Demigod",
        "threat_level": "Global Combat Dominator",
        "affiliation": "Justice League / Themyscira",
        "base_of_operations": "Paradise Island / Washington D.C.",
        "primary_powers": "Superhuman strength, invulnerability, supersonic flight, divine combat mastery",
        "tactical_vulnerability": "Piercing weapons (divine origin bypass), binding by her own lasso",
        "signature_gear": "Lasso of Truth, Bracelets of Submission, God-Killer Broadsword",
        "tactical_profile": "Classical martial supremacy, shield bashes, divine shockwave projection",
        "psychological_dossier": "Diplomatic, fierce warrior spirit, compassionate truth-seeker",
        "image": "comics/wonderwoman.jpg"
    },
    {
        "id": 14,
        "alias": "The Flash",
        "civilian_name": "Barry Allen",
        "origin_era": 1956,
        "classification": "Speed Force Kinetic Conduit",
        "threat_level": "Universal Chronological Disruptor",
        "affiliation": "Justice League / Central City Police",
        "base_of_operations": "Central City / S.T.A.R. Labs",
        "primary_powers": "Near-infinite speed, quantum vibration phasing, time travel, vortex generation",
        "tactical_vulnerability": "Extreme cold (molecular slowing), friction dampening, chronal paradoxes",
        "signature_gear": "Friction-Resistant Ring Suit, Cosmic Treadmill Interface",
        "tactical_profile": "Relativistic kinetic strikes, temporal displacement, intangible bypass",
        "psychological_dossier": "Optimistic, analytical scientist, cautious, plagued by temporal guilt",
        "image": "comics/flash.jpg"
    },
    {
        "id": 15,
        "alias": "Green Lantern",
        "civilian_name": "Hal Jordan",
        "origin_era": 1959,
        "classification": "Cosmic Willpower Energy Conduit",
        "threat_level": "Planetary Vanguard / Sector Law Enforcer",
        "affiliation": "Green Lantern Corps / Justice League",
        "base_of_operations": "Coast City / Sector 2814 / Oa",
        "primary_powers": "Solid-light construct creation, faster-than-light flight, planetary life-support shielding",
        "tactical_vulnerability": "24-hour ring charge depletion, extreme fear-induced emotional instability",
        "signature_gear": "Oan Power Ring, Green Lantern Power Battery",
        "tactical_profile": "Tactical hard-light aviation constructs, dogfighting maneuvers, force fields",
        "psychological_dossier": "Brash, fearless, obstinately stubborn test pilot with indomitable willpower",
        "image": "comics/greenlantern.jpg"
    },
    {
        "id": 16,
        "alias": "Aquaman",
        "civilian_name": "Arthur Curry / Orin",
        "origin_era": 1941,
        "classification": "Atlantean-Human Royal Hybrid",
        "threat_level": "Global Strategic Monarch / Oceanic Sovereign",
        "affiliation": "Justice League / Kingdom of Atlantis",
        "base_of_operations": "Atlantis / Amnesty Bay Lighthouse",
        "primary_powers": "Marine telepathy, deep-sea invulnerability, superhuman strength, hyper-velocity swimming",
        "tactical_vulnerability": "Severe cellular dehydration under prolonged extreme heat, Atlantean dark magic",
        "signature_gear": "Trident of Poseidon (Divine Conduit), A-Symbol Scaled Chainmail",
        "tactical_profile": "Polearm melee mastery, hydrokinetic wave projection, commanding apex predators",
        "psychological_dossier": "Gruff, pragmatic sovereign caught between two worlds, protective of oceans",
        "image": "comics/aquaman.jpg"
    },
    {
        "id": 17,
        "alias": "Martian Manhunter",
        "civilian_name": "J'onn J'onzz / John Jones",
        "origin_era": 1955,
        "classification": "Extraterrestrial Green Martian Archetype",
        "threat_level": "Extinction-Level / Planetary Telepathic Safeguard",
        "affiliation": "Justice League",
        "base_of_operations": "Denver, Colorado / The Watchtower",
        "primary_powers": "Planetary telepathy, density shifting (phasing/intangibility), shapeshifting, Martian vision",
        "tactical_vulnerability": "Pyrophobia (psychological and physical vulnerability to open fire and extreme heat)",
        "signature_gear": "Martian Telepathic Focus Crystal, Royal Chest-Harness",
        "tactical_profile": "Invisible phased infiltration, neural paralysis, brute-force kinetic shape alteration",
        "psychological_dossier": "Stoic, philosophical, sorrowful survivor of Martian genocide, empathetic anchor",
        "image": "comics/martianmanhunter.jpg"
    },
    {
        "id": 18,
        "alias": "Cyborg",
        "civilian_name": "Victor Stone",
        "origin_era": 1980,
        "classification": "Mother Box Technorganic Entity",
        "threat_level": "Planetary Grid Takeover / Universal Uplink",
        "affiliation": "Justice League / Teen Titans",
        "base_of_operations": "Detroit / S.T.A.R. Labs",
        "primary_powers": "Technopathy, white noise acoustic cannon, boom tube teleportation, adaptive cybernetic limbs",
        "tactical_vulnerability": "EMP shockwaves, alien software viruses, loss of biological humanity",
        "signature_gear": "Integrated Apokoliptian Mother Box Architecture",
        "tactical_profile": "Heavy sonic artillery, remote defense hacking, instantaneous squad teleportation",
        "psychological_dossier": "Resilient, struggling between synthetic logic and human emotion",
        "image": "comics/cyborg.jpg"
    },
    {
        "id": 19,
        "alias": "Green Arrow",
        "civilian_name": "Oliver Queen",
        "origin_era": 1941,
        "classification": "Peak Human / Ballistic Marksman",
        "threat_level": "Urban Asymmetric Combatant",
        "affiliation": "Justice League / Team Arrow",
        "base_of_operations": "Star City",
        "primary_powers": "Master archery, tactical stealth, asymmetric guerilla warfare, acrobatic marksmanship",
        "tactical_vulnerability": "Human fragility, limited ammunition payload",
        "signature_gear": "Compound Recurve Bow, Trick Arrows (Thermite, EMP, Net, Boxing Glove)",
        "tactical_profile": "Rooftop perimeter containment, trick-shot trajectory traps, non-lethal suppression",
        "psychological_dossier": "Passionate socialist, defiant rebel, stubborn champion of the forgotten",
        "image": "comics/greenarrow.jpg"
    },
    {
        "id": 20,
        "alias": "Lex Luthor",
        "civilian_name": "Alexander Joseph Luthor",
        "origin_era": 1940,
        "classification": "Apex Human Industrialist / Warsuit Tactician",
        "threat_level": "Global Extinction Threat / Strategic Anti-God",
        "affiliation": "Legion of Doom / Injustice League",
        "base_of_operations": "Metropolis / LexCorp Tower",
        "primary_powers": "12th-level intellect, corporate resource dominance, advanced energy weapon synthesis",
        "tactical_vulnerability": "Mortal body without armor, obsessive pathological narcissism regarding Superman",
        "signature_gear": "Kryptonite-Infused Warsuit, Apokoliptian Energy Cannons",
        "tactical_profile": "High-altitude heavy artillery, radiation zoning, tactical resource attrition",
        "psychological_dossier": "Megalomanic xenophobe, fiercely proud humanist, spite-driven visionary",
        "image": "comics/lexluthor.jpg"
    },
    {
        "id": 21,
        "alias": "Invincible",
        "civilian_name": "Mark Grayson",
        "origin_era": 2003,
        "classification": "Viltrumite-Human Hybrid",
        "threat_level": "Planetary Vanguard / High-Level Viltrumite",
        "affiliation": "Global Defense Agency / Coalition of Planets",
        "base_of_operations": "Suburban Maryland / Earth (Dimension-0)",
        "primary_powers": "Superhuman strength, supersonic-to-interstellar flight, near-invulnerability, cellular regeneration",
        "tactical_vulnerability": "High-frequency inner-ear equilibrium disruption, synthetic Klaxus plant toxins",
        "signature_gear": "Reinforced GDA Kevlar-Spandex Suit",
        "tactical_profile": "Brutal close-quarters brawling, aerial kinetic tackling, pain-threshold endurance",
        "psychological_dossier": "Empathetic, self-sacrificing, burdened by alien lineage and patricidal trauma",
        "image": "comics/invincible.jpg"
    },
    {
        "id": 22,
        "alias": "Omni-Man",
        "civilian_name": "Nolan Grayson",
        "origin_era": 2003,
        "classification": "Pureblooded Viltrumite Conqueror",
        "threat_level": "Planetary Subjugator / High Viltrumite Champion",
        "affiliation": "Viltrum Empire (Formerly) / Coalition of Planets",
        "base_of_operations": "Viltrum High Command / Earth",
        "primary_powers": "Interstellar flight, near-infinite strength and durability, millenia-long lifespan",
        "tactical_vulnerability": "Inner ear high-frequency sonic resonance, high-heat stellar core plasma",
        "signature_gear": "Viltrumite High-Command Insignia Uniform",
        "tactical_profile": "Lethal anatomical decimation, supersonic shockwave flight charges, shock warfare",
        "psychological_dossier": "Darwinian conqueror gradually cracked by human paternal attachment",
        "image": "comics/omniman.jpg"
    },
    {
        "id": 23,
        "alias": "Atom Eve",
        "civilian_name": "Samantha Eve Wilkins",
        "origin_era": 2003,
        "classification": "Sub-Atomic Molecular Transmutator",
        "threat_level": "Omega-Level Matter Architect",
        "affiliation": "Teen Team / Guardians of the Globe",
        "base_of_operations": "Upstate New York / Africa Oasis",
        "primary_powers": "Total atomic rearrangement of non-organic matter, flight, force fields, construct synthesis",
        "tactical_vulnerability": "Mental block preventing manipulation of conscious living tissue (except during near-death trauma)",
        "signature_gear": "Molecular-Resonant Pink Bodysuit",
        "tactical_profile": "Transmuting atmosphere into shields, terrain weaponization, mid-air construct barriers",
        "psychological_dossier": "Idealistic humanitarian, fiercely independent, rejects government militarization",
        "image": "comics/atomeve.jpg"
    },
    {
        "id": 24,
        "alias": "Grand Regent Thragg",
        "civilian_name": "Thragg",
        "origin_era": 2010,
        "classification": "Pureblooded Apex Viltrumite",
        "threat_level": "Intergalactic Emperor / Planetary Annihilator",
        "affiliation": "The Viltrum Empire",
        "base_of_operations": "Viltrum High Command / Thraxa",
        "primary_powers": "Peerless physical strength, FTL interstellar flight, absolute physical durability",
        "tactical_vulnerability": "Direct submersion in stellar core temperatures, internal ear sonic disruptions",
        "signature_gear": "Regent Battle Mantle, Viltrumite Royal Crest",
        "tactical_profile": "Biological decapitation, high-speed bifurcation, military shock tactics",
        "psychological_dossier": "Ruthlessly pragmatic social-Darwinist, devoid of mercy, imperial purity",
        "image": "comics/thragg.jpg"
    },
    {
        "id": 25,
        "alias": "Battle Beast",
        "civilian_name": "Thokk",
        "origin_era": 2004,
        "classification": "Extraterrestrial Feline Berserker",
        "threat_level": "Cosmic Combat Apex / Viltrumite-Breaker",
        "affiliation": "Independent Combat Hunter",
        "base_of_operations": "Galactic Space / Arena Worlds",
        "primary_powers": "Superhuman strength matching Viltrumite high-tiers, endless stamina, impervious hide",
        "tactical_vulnerability": "Addiction to honorable combat leading to self-inflicted handicaps",
        "signature_gear": "Dual Broadswords, Weighted Spiked Mace",
        "tactical_profile": "Savage disembowelment, close-quarters cleaving, relentless pain resistance",
        "psychological_dossier": "Honor-bound zealot, lives exclusively to find a combatant capable of killing him",
        "image": "comics/battlebeast.jpg"
    },
    {
        "id": 26,
        "alias": "Robot",
        "civilian_name": "Rudolph 'Rudy' Conners",
        "origin_era": 2003,
        "classification": "Cybernetic Hivemind / Clone Polymath",
        "threat_level": "Global Strategic Hegemony / AI Overlord",
        "affiliation": "Guardians of the Globe / Global Defense Agency",
        "base_of_operations": "The Pentagon / Subterranean Cyber Fortress",
        "primary_powers": "Super-genius intellect, multi-drone drone neural networking, high-tech weapon engineering",
        "tactical_vulnerability": "Original frail human biological host vulnerability, algorithmic moral inflexibility",
        "signature_gear": "Autonomous Drone Army, Flaxan-Enhanced Exosuits",
        "tactical_profile": "Mathematical attrition, multi-angle drone encirclement, sonic resonance emitters",
        "psychological_dossier": "Coldly utilitarian utilitarian, justifies tyranny for global stability",
        "image": "comics/robot.jpg"
    },
    {
        "id": 27,
        "alias": "Rex Splode",
        "civilian_name": "Rex Sloan",
        "origin_era": 2003,
        "classification": "Bio-Kinetic Molecular Charger",
        "threat_level": "Urban Demolitionist / Commando",
        "affiliation": "Teen Team / Guardians of the Globe",
        "base_of_operations": "GDA Training Facility, Utah",
        "primary_powers": "Accelerating potential kinetic energy into explosive detonation via touch",
        "tactical_vulnerability": "Standard human physical frailty, reckless self-sacrificing impulses",
        "signature_gear": "Charged Titanium Marbles, Explosive Throwing Pins",
        "tactical_profile": "Area denial, explosive projectile scattering, close-range suicide charges",
        "psychological_dossier": "Cocky, abrasive exterior masking trauma and selfless courage",
        "image": "comics/rexsplode.jpg"
    },
    {
        "id": 28,
        "alias": "Monster Girl",
        "civilian_name": "Amanda",
        "origin_era": 2004,
        "classification": "Cursed Metamorphic Ogre Hybrid",
        "threat_level": "Heavy Brawler / Tactical Brute",
        "affiliation": "Guardians of the Globe",
        "base_of_operations": "GDA Headquarters",
        "primary_powers": "Transformation into a towering horned ogre, dense muscle mass, seismic strength",
        "tactical_vulnerability": "De-aging curse (she grows physically younger each time she transforms into the beast)",
        "signature_gear": "Reinforced GDA Stretch Armor",
        "tactical_profile": "Overwhelming grappling, structural body slams, shockwave stomps",
        "psychological_dossier": "Bitter regarding her physical juvenile body, emotionally guarded, battle-hardened",
        "image": "comics/monstergirl.jpg"
    },
    {
        "id": 29,
        "alias": "The Immortal",
        "civilian_name": "Unknown (Former Abraham Lincoln)",
        "origin_era": 2003,
        "classification": "Cosmic-Anomalous True Immortal",
        "threat_level": "Continental Vanguard / Millennial Veteran",
        "affiliation": "Guardians of the Globe",
        "base_of_operations": "Guardians Citadel, Utah",
        "primary_powers": "Biological immortality, flight, enhanced physical strength and invulnerability, centuries of combat",
        "tactical_vulnerability": "Decapitation (causes stasis until head is reattached to torso)",
        "signature_gear": "Classic Blue/Gold Vanguard Tunic",
        "tactical_profile": "Direct aerial brawling, veteran military tactics, head-on vanguard charges",
        "psychological_dossier": "Exhausted by centuries of outliving loved ones, aggressive, duty-bound",
        "image": "comics/immortal.jpg"
    },
    {
        "id": 30,
        "alias": "Allen the Alien",
        "civilian_name": "Allen",
        "origin_era": 2003,
        "classification": "Genetically Engineered Unopan Super-Soldier",
        "threat_level": "Cosmic / Coalition Apex Champion",
        "affiliation": "Coalition of Planets",
        "base_of_operations": "Talescria / Coalition Fleet",
        "primary_powers": "Reactive biological adaptation (grows stronger after recovering from mortal injuries), FTL flight",
        "tactical_vulnerability": "Initial kinetic thresholds before suffering reactive evolution",
        "signature_gear": "Coalition Telepathic Ear-Comm, Void Jumpsuit",
        "tactical_profile": "Heavy cosmic brawling, endurance slugging, atmospheric charges",
        "psychological_dossier": "Easygoing, optimistic, fiercely loyal champion of interplanetary freedom",
        "image": "comics/allenthealien.jpg"
    },
    {
        "id": 31,
        "alias": "Homelander",
        "civilian_name": "John Gillman",
        "origin_era": 2006,
        "classification": "Compound V Engineered Apex Metahuman",
        "threat_level": "Global Extinction Threat / Rogue Godhead Tier",
        "affiliation": "The Seven / Vought International",
        "base_of_operations": "Vought Tower, New York City",
        "primary_powers": "Godlike strength, thermal laser vision, hypersonic flight, super-audition, invulnerability",
        "tactical_vulnerability": "Total lack of combat discipline, deep narcissistic fragility, desperate need for adoration",
        "signature_gear": "Vought Patriotic Flag-Cape Suit",
        "tactical_profile": "Lethal laser sweeps, crushing kinetic strikes, psychological terror",
        "psychological_dossier": "Megalomanic, emotionally stunted, sociopathic, violent craving for validation",
        "image": "comics/homelander.jpg"
    },
    {
        "id": 32,
        "alias": "Billy Butcher",
        "civilian_name": "William J. Butcher",
        "origin_era": 2006,
        "classification": "Compound V Enhanced Black-Ops Vigilante",
        "threat_level": "Asymmetric Guerilla Terror / Supe-Killer",
        "affiliation": "The Boys / The CIA",
        "base_of_operations": "The Flatiron Safehouse, New York City",
        "primary_powers": "Compound V-boosted strength/durability, master psychological warfare, torture specialist",
        "tactical_vulnerability": "Mortal base biology, self-destructive single-minded vengeance",
        "signature_gear": "Heavy Crowbar, Combat Trenchcoat, Customized High-Caliber Shotgun",
        "tactical_profile": "Ruthless blackmail, asymmetric traps, point-blank blunt executions",
        "psychological_dossier": "Monstrously driven, charmingly sociopathic, genocidal hatred toward all Supes",
        "image": "comics/butcher.jpg"
    },
    {
        "id": 33,
        "alias": "Queen Maeve",
        "civilian_name": "Maggie Shaw",
        "origin_era": 2006,
        "classification": "Compound V High-Tier Paragon",
        "threat_level": "Continental Heavy / Second of the Seven",
        "affiliation": "The Seven (Formerly) / Resistance",
        "base_of_operations": "Vought Tower, New York City",
        "primary_powers": "Colossal physical strength, dense invulnerable tissue, martial arts mastery",
        "tactical_vulnerability": "Depowerment via extreme radiation blasts, deep existential cynicism",
        "signature_gear": "Amazonian-Style Steel Armor, Broadsword",
        "tactical_profile": "Heavy hand-to-hand brawling, shield bashes, tactical disarming",
        "psychological_dossier": "Disillusioned alcoholic, deeply self-loathing, buried ember of true heroism",
        "image": "comics/queenmaeve.jpg"
    },
    {
        "id": 34,
        "alias": "Starlight",
        "civilian_name": "Annie January",
        "origin_era": 2006,
        "classification": "Compound V Engineered Metahuman",
        "threat_level": "High-Rank Regional Metahuman (Vought Tier-1)",
        "affiliation": "The Seven (Defected) / The Boys Resistance",
        "base_of_operations": "New York City / Vought Tower",
        "primary_powers": "Bioluminescent photon light blasts, electrical energy absorption, superhuman durability",
        "tactical_vulnerability": "Requires active electrical grids to recharge optic blasts, heavy anti-materiel ordnance",
        "signature_gear": "Vought-Designed White/Gold Hero Suit, Heavy Gauntlets",
        "tactical_profile": "Blinding optical flashes, concussive repulsor beams, defensive hand-to-hand",
        "psychological_dossier": "Disillusioned idealist, courageous whistleblower, resilient under intimidation",
        "image": "comics/starlight.jpg"
    },
    {
        "id": 35,
        "alias": "Black Noir",
        "civilian_name": "Classified / Clone Contingency",
        "origin_era": 2006,
        "classification": "Compound V Stealth Infiltrator & Assassin",
        "threat_level": "Apex Supe-Executioner",
        "affiliation": "The Seven / Vought Black-Ops",
        "base_of_operations": "Vought Tower Shadow Compartment",
        "primary_powers": "Enhanced strength matching Homelander, pain immunity, superhuman agility, martial mastery",
        "tactical_vulnerability": "Tree nut allergy (severe anaphylaxis), severe brain trauma / dissociation",
        "signature_gear": "Full-Body Matte-Black Stealth Armor, Throwing Daggers, Katana Array",
        "tactical_profile": "Silent stalking, instantaneous close-quarters anatomical shredding",
        "psychological_dossier": "Completely mute, clinically psychopathic, obedient corporate executioner",
        "image": "comics/blacknoir.jpg"
    },
    {
        "id": 36,
        "alias": "Soldier Boy",
        "civilian_name": "Ben",
        "origin_era": 2006,
        "classification": "WWII Compound V Original Super-Soldier",
        "threat_level": "Planetary Kinetic Threat / Supe Depowerer",
        "affiliation": "Payback (Formerly) / Vought International",
        "base_of_operations": "Russian Cryo-Facility / Elgin, Ohio",
        "primary_powers": "Massive physical strength, radioactive chest beam capable of burning Compound V from blood",
        "tactical_vulnerability": "PTSD flashbacks, Novichok nerve gas sedative",
        "signature_gear": "Heavy Gold-Plated Eagle Shield, Custom Trench Knife",
        "tactical_profile": "Direct blunt trauma beatdowns, kinetic shield strikes, radioactive area blasts",
        "psychological_dossier": "Toxic, narcissistic, dated 1940s mentality, aggressive survivalist",
        "image": "comics/soldierboy.jpg"
    },
    {
        "id": 37,
        "alias": "A-Train",
        "civilian_name": "Reggie Franklin",
        "origin_era": 2006,
        "classification": "Compound V Speedster Metahuman",
        "threat_level": "Supersonic Urban Hazard",
        "affiliation": "The Seven / Vought International",
        "base_of_operations": "Vought Tower, New York City",
        "primary_powers": "Mach-3 running speed, accelerated kinetic reflexes, enhanced physical impact density",
        "tactical_vulnerability": "Compound V addiction causing cardiovascular failure, fragile leg bones under torque",
        "signature_gear": "Aerodynamic Blue Track Suit, Kinetic Heart Monitor",
        "tactical_profile": "High-speed body checks, blitzing past human perception, kinetic drags",
        "psychological_dossier": "Insecure, terrified of losing fame and status, morally weak",
        "image": "comics/atrain.jpg"
    },
    {
        "id": 38,
        "alias": "Kimiko",
        "civilian_name": "Kimiko Miyashiro",
        "origin_era": 2006,
        "classification": "Forced Compound V Ingestion Metahuman",
        "threat_level": "Lethal Urban Assassin / Regenerative Brawler",
        "affiliation": "The Boys / Shining Light Liberation (Formerly)",
        "base_of_operations": "The Flatiron Safehouse, New York City",
        "primary_powers": "Near-instantaneous cellular regeneration, superhuman agility, ferocious claw strikes",
        "tactical_vulnerability": "Mute, psychological trauma regarding human experimentation",
        "signature_gear": "Civilian Street Clothes, Concealed Knives",
        "tactical_profile": "Guerilla ambush, ripping limbs/throats bare-handed, absorbing fatal damage",
        "psychological_dossier": "Protective, deeply traumatized, silent guardian of those she trusts",
        "image": "comics/kimiko.jpg"
    },
    {
        "id": 39,
        "alias": "Stormfront",
        "civilian_name": "Klara Risinger",
        "origin_era": 2006,
        "classification": "Original 1930s Nazi Compound V Prototype",
        "threat_level": "Planetary Ideological & Electrokinetic Calamity",
        "affiliation": "The Seven / Payback (Formerly)",
        "base_of_operations": "Berlin / Vought Tower",
        "primary_powers": "Plasma-lightning generation, flight, near-invulnerability, decelerated aging",
        "tactical_vulnerability": "Unprotected human eyes (soft tissue knife vulnerability), high-voltage ground out",
        "signature_gear": "Vought-Modernized Black Battle Suit",
        "tactical_profile": "Ranged electro-plasma bombardment, crowd-control lightning arcs",
        "psychological_dossier": "Unrepentant Nazi supremacist, master manipulator of modern digital propaganda",
        "image": "comics/stormfront.jpg"
    },
    {
        "id": 40,
        "alias": "The Deep",
        "civilian_name": "Kevin Moskowitz",
        "origin_era": 2006,
        "classification": "Compound V Marine Metahuman",
        "threat_level": "Coastal Threat / Vought PR Puppet",
        "affiliation": "The Seven / Vought International",
        "base_of_operations": "Sandusky, Ohio / Vought Tower",
        "primary_powers": "Aquatic telepathy, underwater respiration, deep-sea pressure resistance, enhanced swimming",
        "tactical_vulnerability": "Physical gills on torso (extremely sensitive weak points), pathetic self-esteem",
        "signature_gear": "Scaled Wet-Suit with Golden Accents",
        "tactical_profile": "Summoning sea creatures for distractions, underwater melee",
        "psychological_dossier": "Desperate for validation, easily manipulated, shallow and cowardly",
        "image": "comics/thedeep.jpg"
    },
    {
        "id": 41,
        "alias": "Hellboy",
        "civilian_name": "Anung Un Rama",
        "origin_era": 1993,
        "classification": "Cambion Demon / Occult Paranatural",
        "threat_level": "Supernatural Urban Enforcer / Latent Apocalyptic Harbinger",
        "affiliation": "Bureau for Paranormal Research and Defense (B.P.R.D.)",
        "base_of_operations": "B.P.R.D. Headquarters, Fairfield, Connecticut",
        "primary_powers": "Superhuman durability, thermal immunity to fire/lava, accelerated healing factor",
        "tactical_vulnerability": "Destiny compulsion tied to the Right Hand of Doom, ancient blood curses",
        "signature_gear": "The Right Hand of Doom (Indestructible Relic), 'Good Samaritan' 22mm Revolver",
        "tactical_profile": "Heavy blunt-force brawling, esoteric occult knowledge, improvisational demolition",
        "psychological_dossier": "Cynical, blue-collar pragmatist, weary of supernatural destiny, loves cats and pancakes",
        "image": "comics/hellboy.jpg"
    },
    {
        "id": 42,
        "alias": "Abe Sapien",
        "civilian_name": "Langdon Everett Caul",
        "origin_era": 1994,
        "classification": "Ichthyo-Sapiens Amphibious Metahuman",
        "threat_level": "Field Specialist / Occult Aquatic Operative",
        "affiliation": "Bureau for Paranormal Research and Defense (B.P.R.D.)",
        "base_of_operations": "B.P.R.D. Aquatic Enclosure, Connecticut",
        "primary_powers": "Underwater respiration, deep-sea pressure immunity, hyper-swimming speed, psychometry",
        "tactical_vulnerability": "Severe dehydration from prolonged dry air, vulnerability to arid climates",
        "signature_gear": "B.P.R.D. Water-Recirculation Suit, Custom Underwater Sidearm, Harpoon Darts",
        "tactical_profile": "Tactical firearms marksmanship, spear-fighting melee, forensic psychometric tracking",
        "psychological_dossier": "Cultured scholar, gentle and observant, struggling with past-life revelations",
        "image": "comics/abesapien.jpg"
    },
    {
        "id": 43,
        "alias": "Liz Sherman",
        "civilian_name": "Elizabeth Sherman",
        "origin_era": 1994,
        "classification": "Pyrokinetic Human Nexus",
        "threat_level": "Apocalyptic Conflagration / WMD Pyrokinetic",
        "affiliation": "B.P.R.D.",
        "base_of_operations": "B.P.R.D. Headquarters, Connecticut",
        "primary_powers": "Summoning and manipulating primordial fire, thermal absorption, fire immunity",
        "tactical_vulnerability": "Emotional trauma causing catastrophic uncontrolled fire bursts, spiritual exhaustion",
        "signature_gear": "B.P.R.D. Pyro-Dampening Belt, Tactical Holster",
        "tactical_profile": "Wide-area thermal incineration, targeted fireballs, heat barriers",
        "psychological_dossier": "Haunted by childhood tragedy, reclusive, finds family within the B.P.R.D.",
        "image": "comics/lizsherman.jpg"
    },
    {
        "id": 44,
        "alias": "Johann Kraus",
        "civilian_name": "Johann Kraus",
        "origin_era": 2002,
        "classification": "Ectoplasmic Spirit Medium",
        "threat_level": "Ethereal Infiltrator / Ghost Conduit",
        "affiliation": "B.P.R.D.",
        "base_of_operations": "B.P.R.D. Headquarters, Connecticut",
        "primary_powers": "Ectoplasmic projection, possessing and animating physical objects/corpses, intangibility",
        "tactical_vulnerability": "Punctures in his containment suit causing ectoplasmic dissipation",
        "signature_gear": "Pressurized Glass-Visor Containment Suit",
        "tactical_profile": "Phasing through solid walls, animating dead remains to fight, vent exploration",
        "psychological_dossier": "Longs for sensory human touch, professional medium, calm under occult horror",
        "image": "comics/johannkraus.jpg"
    },
    {
        "id": 45,
        "alias": "Lobster Johnson",
        "civilian_name": "The Lobster",
        "origin_era": 1999,
        "classification": "Pulp Vigilante / Vengeful Spirit",
        "threat_level": "Urban Supernatural Inquisitor",
        "affiliation": "Independent 1930s Crimefighter",
        "base_of_operations": "New York City (1930s) / Spectral Realm",
        "primary_powers": "Spectral manifestation, marksmanship, supernatural resilience, burning claw brand",
        "tactical_vulnerability": "Ethereal anchors, holy banishment rituals",
        "signature_gear": "Twin .45 Pistols, The Lobster's Claw Branding Iron, Aviator Goggles",
        "tactical_profile": "Dual-pistol gunplay, ruthless interrogation, branding mobsters with his claw",
        "psychological_dossier": "Uncompromising pulp crusader, stern, completely devoted to slaying evil",
        "image": "comics/lobsterjohnson.jpg"
    },
    {
        "id": 46,
        "alias": "Roger the Homunculus",
        "civilian_name": "Roger",
        "origin_era": 1997,
        "classification": "Alchemical Inanimate Homunculus",
        "threat_level": "Heavy Brawler / Ancient Alchemical Construct",
        "affiliation": "B.P.R.D.",
        "base_of_operations": "Caelestra / B.P.R.D. Headquarters",
        "primary_powers": "Immense physical strength, absorbing and discharging raw electrical energy, invulnerable body",
        "tactical_vulnerability": "Draining of internal life-force generator causing catatonic slumber",
        "signature_gear": "Fulcrum Electrical Harness, Heavy Iron Cuffs",
        "tactical_profile": "Crushing stone-grip grappling, absorbing incoming lightning, brute shield",
        "psychological_dossier": "Innocent, child-like wonder, fiercely loyal to Hellboy, eager to do good",
        "image": "comics/roger.jpg"
    },
    {
        "id": 47,
        "alias": "Rasputin",
        "civilian_name": "Grigori Yefimovich Rasputin",
        "origin_era": 1994,
        "classification": "Resurrected Mystic / Conduit of the Dragon",
        "threat_level": "Apocalyptic Summoner / Master Occultist",
        "affiliation": "Project Ragna Rok / Ogdru Jahad Cult",
        "base_of_operations": "Arctic Wastelands / Ragna Rok Strongholds",
        "primary_powers": "Dark magic summoning, spirit possession, channeling the Ogdru Jahad's apocalypse",
        "tactical_vulnerability": "Holy consecrated artifacts, destruction of physical ghost anchors",
        "signature_gear": "Gauntlets of Belial, Occult Summoning Altar",
        "tactical_profile": "Extradimensional monster summoning, mental domination, ritual hexes",
        "psychological_dossier": "Fanatical apocalypticist, manipulative, cold, convinced of new world rebirth",
        "image": "comics/rasputin.jpg"
    },
    {
        "id": 48,
        "alias": "Kroenen",
        "civilian_name": "Karl Ruprecht Kroenen",
        "origin_era": 1994,
        "classification": "Cybernetic-Surgical Masochist Assassin",
        "threat_level": "Clockwork Martial Murderer",
        "affiliation": "Thule Society / Project Ragna Rok",
        "base_of_operations": "Berlin / Hidden Occult Labs",
        "primary_powers": "Clockwork-regulated biology, immune to blood loss/pain, superhuman acrobatic speed",
        "tactical_vulnerability": "Destruction of internal clockwork heart mechanism, magnetic pulse",
        "signature_gear": "Trench Dual Tonfa Blades, Gas Mask / Surgical Bodysuit",
        "tactical_profile": "Blinding spin-slashes, deflecting bullets with tonfa blades, silent ambush",
        "psychological_dossier": "Pathological masochist, surgically addicted to body modification, robotic loyalty",
        "image": "comics/kroenen.jpg"
    },
    {
        "id": 49,
        "alias": "The Black Flame",
        "civilian_name": "Landis Craw / Raimund Diestel",
        "origin_era": 2005,
        "classification": "Occult Primordial Energy Host",
        "threat_level": "Global Calamity / Kaiju-Summoning Conduit",
        "affiliation": "Zinco Corporation / Ogdru Hem",
        "base_of_operations": "New York / Zinco Tower",
        "primary_powers": "Black plasma fire projection, levitation, channeling ancient Ogdru Hem kaiju",
        "tactical_vulnerability": "Overloading the host's physical body through pure light magic",
        "signature_gear": "Black Flame Skeletal Tunic",
        "tactical_profile": "Incinerating entire buildings with dark fire, summoning subterranean horrors",
        "psychological_dossier": "Megalomanic corporate sociopath intoxicated by primordial destruction",
        "image": "comics/blackflame.jpg"
    },
    {
        "id": 50,
        "alias": "Baba Yaga",
        "civilian_name": "Baba Yaga",
        "origin_era": 1998,
        "classification": "Ancient Slavic Mythological Witch",
        "threat_level": "Eldritch Mythic Entity / Soul Devourer",
        "affiliation": "Slavic Spirit Realm",
        "base_of_operations": "Dancing Chicken-Legged Hut / Forest of Russian Myth",
        "primary_powers": "Soul extraction into wooden figurines, dimension weaving, ancient nature curses",
        "tactical_vulnerability": "Desecration of her graveyard soil, destruction of her wooden effigies",
        "signature_gear": "Pestle and Mortar of Flight, Skull Lantern of Souls",
        "tactical_profile": "Curse-casting, summoning undead hordes, illusory trickery",
        "psychological_dossier": "Vengeful ancient crone, deeply spiteful toward Hellboy for shooting her eye out",
        "image": "comics/babayaga.jpg"
    },
    {
        "id": 51,
        "alias": "Darna",
        "civilian_name": "Narda",
        "origin_era": 1950,
        "classification": "Celestial Warrior of Planet Marte",
        "threat_level": "Planetary Guardian / Divine Paragon Tier",
        "affiliation": "Independent Guardian of Earth",
        "base_of_operations": "Barrio San Andres / Manila, Philippines",
        "primary_powers": "Superhuman strength, near-lightspeed flight, bulletproof invulnerability, thermal optic blasts",
        "tactical_vulnerability": "Reversion to mortal human form if the White Pebble is expelled from her mouth",
        "signature_gear": "White Pebble of Marte, Medallion Belt, Winged Deflection Tiara, Ruby Star Bra",
        "tactical_profile": "Acrobatic aerial combat, deflecting projectiles with accessories, non-lethal disarms",
        "psychological_dossier": "Pure-hearted, humble, courageous, deeply rooted in community protection",
        "image": "comics/darna.jpg"
    },
    {
        "id": 52,
        "alias": "Captain Barbell",
        "civilian_name": "Tenteng / Enteng / Arell",
        "origin_era": 1963,
        "classification": "Mystical Magical Barbell Conduit",
        "threat_level": "Planetary Heavy Vanguard / National Champion",
        "affiliation": "Protectors of the Philippine Archipelago",
        "base_of_operations": "Manila, Philippines",
        "primary_powers": "Colossal physical strength, supersonic flight, ballistic invulnerability, optical energy vision",
        "tactical_vulnerability": "Reversion to frail mortal form if separated from the magical barbell or unable to lift it",
        "signature_gear": "Magical Golden Barbell of Herminia",
        "tactical_profile": "Direct kinetic power strikes, aerial swoops, shockwave claps, lifting infrastructure",
        "psychological_dossier": "Meek and self-effacing in civilian life, courageous and resolute when empowered",
        "image": "comics/captainbarbell.jpg"
    },
    {
        "id": 53,
        "alias": "Lastikman",
        "civilian_name": "Eskrima / Larry Martinez",
        "origin_era": 1965,
        "classification": "Extraterrestrial Organic Polymer Polymorph",
        "threat_level": "Metropolitan Urban Protector",
        "affiliation": "Independent Protector of the Metropolis",
        "base_of_operations": "Manila, Philippines",
        "primary_powers": "Total molecular elasticity, bodily shapeshifting, kinetic bounce deflection, mass reformation",
        "tactical_vulnerability": "Sub-zero temperatures causing brittle freezing, concentrated thermal melting",
        "signature_gear": "Black-and-White Checkered Organic Morphing Jumpsuit",
        "tactical_profile": "Ensnarement grappling, rubberized catapult strikes, morphing into gliders and barriers",
        "psychological_dossier": "Playful, lighthearted, clever, deeply affectionate toward human civilization",
        "image": "comics/lastikman.jpg"
    },
    {
        "id": 54,
        "alias": "Dyesebel",
        "civilian_name": "Dyesebel",
        "origin_era": 1952,
        "classification": "Siren-Human Amphibious Metahuman",
        "threat_level": "Oceanic Sentinel / Aquatic Sovereign",
        "affiliation": "Kingdom of the Deep / Human Protectors",
        "base_of_operations": "Philippine Seas / Palawan Waters",
        "primary_powers": "Aquatic telepathy, underwater hyper-mobility, deep-ocean pressure immunity, sea creature empathy",
        "tactical_vulnerability": "Severe dehydration on dry land, loss of mobility when away from salt water",
        "signature_gear": "Enchanted Sea Conch, Coral Headdress",
        "tactical_profile": "Underwater hit-and-run strikes, commanding apex marine life, ocean current manipulation",
        "psychological_dossier": "Compassionate, longing for peaceful harmony between terrestrial and oceanic worlds",
        "image": "comics/dyesebel.jpg"
    },
    {
        "id": 55,
        "alias": "Valentina",
        "civilian_name": "Valentina",
        "origin_era": 1950,
        "classification": "Cursed Gorgon Serpent Queen Hybrid",
        "threat_level": "Regional Calamity / Mythological Metahuman",
        "affiliation": "Serpent Brood",
        "base_of_operations": "Underground Serpent Lairs / Manila",
        "primary_powers": "Venomous prehensile snake hair, petrification gaze, superhuman durability, ophidian telepathy",
        "tactical_vulnerability": "Reflected petrification, severing of her primary master serpent locks",
        "signature_gear": "Serpent Scepter, Concealment Silk Turbans",
        "tactical_profile": "Venomous constriction, commanding swarms of deadly serpents, hypnotic gaze",
        "psychological_dossier": "Vengeful supremacist, bitter, consumed by jealousy toward Darna",
        "image": "comics/valentina.jpg"
    },
    {
        "id": 56,
        "alias": "Varga",
        "civilian_name": "Varga",
        "origin_era": 1947,
        "classification": "Original Planetary Warrior Archetype",
        "threat_level": "Planetary Guardian Pioneer",
        "affiliation": "Independent Protector",
        "base_of_operations": "Luzon, Philippines",
        "primary_powers": "Superhuman strength, leaping over mountains, bulletproof invulnerability, enhanced agility",
        "tactical_vulnerability": "Mortal biological base state when de-transformed",
        "signature_gear": "Golden Tiara, Classic Two-Piece Red Battle Garb",
        "tactical_profile": "Heavy physical punches, acrobatic evasion, defensive blocking",
        "psychological_dossier": "Bold, honorable, pioneer protector against underworld crime and demons",
        "image": "comics/varga.jpg"
    },
    {
        "id": 57,
        "alias": "Flash Bomba",
        "civilian_name": "Roldan",
        "origin_era": 1967,
        "classification": "Mystical Equine-Blessed Giant Brawler",
        "threat_level": "Heavy Municipal Enforcer",
        "affiliation": "Independent Crimefighter",
        "base_of_operations": "Manila, Philippines",
        "primary_powers": "Enormously enlarged hands and feet, seismic shockwave generation, superhuman leaping",
        "tactical_vulnerability": "Reduced precision fine-motor dexterity due to giant appendages",
        "signature_gear": "Heavy Combat Gloves, Reinforced Boots",
        "tactical_profile": "Thunderous ground slams, giant palm shockwave strikes, high-impact jump drops",
        "psychological_dossier": "Determined, overcame physical paralysis through magical Tikbalang blessing",
        "image": "comics/flashbomba.jpg"
    },
    {
        "id": 58,
        "alias": "Tiny Tony",
        "civilian_name": "Tony",
        "origin_era": 1966,
        "classification": "Extraterrestrial-Encounter Sub-Atomic Metahuman",
        "threat_level": "Microscopic Infiltrator / Saboteur",
        "affiliation": "Independent Protector",
        "base_of_operations": "Metro Manila",
        "primary_powers": "Size reduction to sub-inch scale while retaining and multiplying full human density/strength",
        "tactical_vulnerability": "Vulnerability to localized atmospheric vacuums, insect swarms",
        "signature_gear": "Miniature Flight Pack, Micro-Transceiver",
        "tactical_profile": "Entering internal machinery to sabotage components, stealth acoustic infiltration",
        "psychological_dossier": "Clever, resource-oriented, uses size to outmaneuver physically overwhelming foes",
        "image": "comics/tinytony.jpg"
    },
    {
        "id": 59,
        "alias": "Kapitan Bakal",
        "civilian_name": "Bakal",
        "origin_era": 1964,
        "classification": "Forged Iron Armor Cybernetic Warmachine",
        "threat_level": "Heavy Municipal Destructor",
        "affiliation": "Underworld Syndicate",
        "base_of_operations": "Manila Industrial District",
        "primary_powers": "Impenetrable iron plate plating, crushing mechanical grip, weaponized flame blasts",
        "tactical_vulnerability": "Extreme heat causing interior armor oven effect, joint welding via intense lightning",
        "signature_gear": "Cast-Iron Powered Exosuit, Internal Flamethrower Cannons",
        "tactical_profile": "Slow forward marching, crushing infrastructure, close-range flame sweeps",
        "psychological_dossier": "Brutal, uncompromising criminal enforcer seeking dominance over heroes",
        "image": "comics/kapitanbakal.jpg"
    },
    {
        "id": 60,
        "alias": "Dragonna",
        "civilian_name": "Rona",
        "origin_era": 1978,
        "classification": "Draconic Pyrokinetic Avatar",
        "threat_level": "Regional Pyrokinetic Threat",
        "affiliation": "Independent Protector",
        "base_of_operations": "Mindanao / Manila",
        "primary_powers": "Projection of dragon-shaped flame torrents, thermal flight, thermal shield generation",
        "tactical_vulnerability": "Submersion in water (quenches flame output), respiratory smoke inhalation",
        "signature_gear": "Dragon-Scale Bodysuit, Flame Conduit Bracers",
        "tactical_profile": "Aerial fire dive attacks, concentrated plasma streams, explosive area clears",
        "psychological_dossier": "Feisty, passionate, fiercely protective of her heritage and family",
        "image": "comics/dragonna.jpg"
    }
]

@app.get("/")
def home():
    return {
        "registry_status": "ONLINE",
        "dossiers_cataloged": len(heroes_db),
        "features_per_entry": 14,
        "endpoints": ["/heroes", "/heroes/{hero_id}", "/heroes/search"]
    }

@app.get("/heroes", response_model=List[dict])
def get_heroes():
    return heroes_db

@app.get("/heroes/search", response_model=List[dict])
def search_heroes(
    q: Optional[str] = Query(None, description="Global keyword query across all metahuman features"),
    classification: Optional[str] = Query(None, description="Filter strictly by power classification")
):
    results = heroes_db
    if classification:
        c_lower = classification.lower()
        results = [h for h in results if c_lower in h['classification'].lower()]
    if q:
        q_lower = q.lower()
        filtered = []
        for hero in results:
            searchable_text = " ".join([str(v) for v in hero.values()]).lower()
            if q_lower in searchable_text:
                filtered.append(hero)
        results = filtered
    return results

@app.get("/heroes/{hero_id}", response_model=dict)
def get_hero(hero_id: int):
    for hero in heroes_db:
        if hero["id"] == hero_id:
            return hero
    raise HTTPException(status_code=404, detail="Dossier classified or not found.")
