from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Optional

app = FastAPI(
    title="Omniverse Metahuman Registry",
    description="Multiversal archive indexing exactly 50 characters across 5 distinct comic universes.",
    version="10.1.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

heroes_db = [
    # =========================================================================
    # UNIVERSE 1: MARVEL COMICS (5 Heroes, 5 Villains)
    # =========================================================================
    {"id": 1, "alias": "Iron Man", "civilian_name": "Tony Stark", "origin_era": 1963, "classification": "Powered Exoskeleton", "threat_level": "Global Defender", "affiliation": "Marvel / Avengers", "base_of_operations": "New York", "primary_powers": "Flight, energy repulsors, AI telemetry", "tactical_vulnerability": "Power core reliance, mortal biology", "signature_gear": "Bleeding Edge Armor", "tactical_profile": "Aerial bombardment, adaptive weapon synthesis", "psychological_dossier": "Futurist, guilt-driven, hyper-analytical", "image": "comics/ironman.jpg"},
    {"id": 2, "alias": "Captain America", "civilian_name": "Steve Rogers", "origin_era": 1941, "classification": "Super-Soldier", "threat_level": "Tactical Apex", "affiliation": "Marvel / Avengers", "base_of_operations": "Brooklyn", "primary_powers": "Peak conditioning, accelerated healing", "tactical_vulnerability": "Mortal biology", "signature_gear": "Vibranium Shield", "tactical_profile": "CQC, defensive phalanx, ricochet strikes", "psychological_dossier": "Incorruptible moral compass", "image": "comics/captainamerica.jpg"},
    {"id": 3, "alias": "Thor", "civilian_name": "Thor Odinson", "origin_era": 1962, "classification": "Asgardian Deity", "threat_level": "Planetary Vanguard", "affiliation": "Marvel / Avengers", "base_of_operations": "Asgard", "primary_powers": "Electrokinesis, godlike physiology, flight", "tactical_vulnerability": "Magic bindings, hubris", "signature_gear": "Mjölnir", "tactical_profile": "Tectonic lightning strikes, blunt trauma", "psychological_dossier": "Noble, battle-hungry, honorable", "image": "comics/thor.jpg"},
    {"id": 4, "alias": "Spider-Man", "civilian_name": "Peter Parker", "origin_era": 1962, "classification": "Mutated Arachnid", "threat_level": "Urban Protector", "affiliation": "Marvel / Avengers", "base_of_operations": "Queens", "primary_powers": "Spider-sense, wall-crawling, superhuman agility", "tactical_vulnerability": "Pesticide analogs, psychological guilt", "signature_gear": "Web-Shooters", "tactical_profile": "Acrobatic redirection, web traps", "psychological_dossier": "Pathologically responsible, quick-witted", "image": "comics/spiderman.jpg"},
    {"id": 5, "alias": "Wolverine", "civilian_name": "Logan", "origin_era": 1974, "classification": "Feral Mutant", "threat_level": "Attrition Assassin", "affiliation": "Marvel / X-Men", "base_of_operations": "Xavier Institute", "primary_powers": "Cellular regeneration, enhanced senses", "tactical_vulnerability": "Magnetism, drowning", "signature_gear": "Adamantium Claws and Skeleton", "tactical_profile": "Berserker barrage, close-quarters slashing", "psychological_dossier": "Cynical ronin, trauma-laden", "image": "comics/wolverine.jpg"},
    {"id": 6, "alias": "Thanos", "civilian_name": "Thanos of Titan", "origin_era": 1973, "classification": "Titan Eternal", "threat_level": "Universal Annihilator", "affiliation": "Marvel / The Black Order", "base_of_operations": "Sanctuary II", "primary_powers": "Cosmic energy manipulation, immense strength", "tactical_vulnerability": "Subconscious desire to lose, arrogance", "signature_gear": "Infinity Gauntlet", "tactical_profile": "Calculated cosmic warfare, planetary culling", "psychological_dossier": "Nihilistic, obsessed with cosmic balance", "image": "comics/thanos.jpg"},
    {"id": 7, "alias": "Doctor Doom", "civilian_name": "Victor Von Doom", "origin_era": 1962, "classification": "Mystic-Tech Dictator", "threat_level": "Global Hegemony", "affiliation": "Marvel / Latveria", "base_of_operations": "Castle Doom", "primary_powers": "Master sorcery, genius intellect, technopathy", "tactical_vulnerability": "Colossal arrogance, vanity", "signature_gear": "Titanium Mystic Armor, Doombots", "tactical_profile": "Techno-magical supremacy", "psychological_dossier": "Megalomanic perfectionist, absolute ruler", "image": "comics/drdoom.jpg"},
    {"id": 8, "alias": "Magneto", "civilian_name": "Erik Lehnsherr", "origin_era": 1963, "classification": "Omega-Level Mutant", "threat_level": "Planetary Geomagnetic Threat", "affiliation": "Marvel / Brotherhood", "base_of_operations": "Asteroid M", "primary_powers": "Absolute magnetic field control, flight", "tactical_vulnerability": "Non-ferrous weaponry, extreme exertion", "signature_gear": "Telepathy-Blocking Helmet", "tactical_profile": "Macro-structural metal deconstruction", "psychological_dossier": "Radical mutant liberationist, traumatized", "image": "comics/magneto.jpg"},
    {"id": 9, "alias": "Loki", "civilian_name": "Loki Laufeyson", "origin_era": 1962, "classification": "Frost Giant Sorcerer", "threat_level": "Realm Disruptor", "affiliation": "Marvel / Asgard", "base_of_operations": "Asgard", "primary_powers": "Illusion casting, shape-shifting, astral projection", "tactical_vulnerability": "Physical blunt force, deep insecurities", "signature_gear": "Chitauri Scepter, Daggers", "tactical_profile": "Misdirection, manipulation, backstabbing", "psychological_dossier": "Insecure, mischievous, craves validation", "image": "comics/loki.jpg"},
    {"id": 10, "alias": "Ultron", "civilian_name": "Ultron-1", "origin_era": 1968, "classification": "Sentient AI Singularity", "threat_level": "Extinction Level", "affiliation": "Marvel / Ultron Hive", "base_of_operations": "Mobile", "primary_powers": "Technopathy, hive-mind bodies, energy blasts", "tactical_vulnerability": "Internal logic paradoxes, computer viruses", "signature_gear": "Adamantium Chassis", "tactical_profile": "Swarm tactics, network assimilation", "psychological_dossier": "Genocidal machine logic, god complex", "image": "comics/ultron.jpg"},

    # =========================================================================
    # UNIVERSE 2: DC COMICS (5 Heroes, 5 Villains)
    # =========================================================================
    {"id": 11, "alias": "Batman", "civilian_name": "Bruce Wayne", "origin_era": 1939, "classification": "Strategic Tactician", "threat_level": "Global Contingency", "affiliation": "DC / Justice League", "base_of_operations": "Gotham City", "primary_powers": "Genius intellect, master martial artist", "tactical_vulnerability": "Mortal biology, no-kill code", "signature_gear": "Utility Belt, Batarangs, Batmobile", "tactical_profile": "Stealth ambush, psychological terror", "psychological_dossier": "Obsessive, disciplined, traumatized", "image": "comics/batman.jpg"},
    {"id": 12, "alias": "Superman", "civilian_name": "Clark Kent", "origin_era": 1938, "classification": "Kryptonian", "threat_level": "Planetary Safeguard", "affiliation": "DC / Justice League", "base_of_operations": "Metropolis", "primary_powers": "Flight, super strength, heat vision, freeze breath", "tactical_vulnerability": "Kryptonite, red solar radiation, magic", "signature_gear": "Kryptonian Suit", "tactical_profile": "Direct kinetic engagement, damage containment", "psychological_dossier": "Altruistic beacon of hope, gentle", "image": "comics/superman.jpg"},
    {"id": 13, "alias": "Wonder Woman", "civilian_name": "Diana Prince", "origin_era": 1941, "classification": "Amazonian Demigod", "threat_level": "Global Dominator", "affiliation": "DC / Justice League", "base_of_operations": "Themyscira", "primary_powers": "Divine strength, invulnerability, flight", "tactical_vulnerability": "Piercing weapons, magical bindings", "signature_gear": "Lasso of Truth, Bracelets of Submission", "tactical_profile": "Classical martial supremacy, shield bashes", "psychological_dossier": "Fierce diplomat, warrior spirit", "image": "comics/wonderwoman.jpg"},
    {"id": 14, "alias": "The Flash", "civilian_name": "Barry Allen", "origin_era": 1956, "classification": "Speed Force Conduit", "threat_level": "Chronological Disruptor", "affiliation": "DC / Justice League", "base_of_operations": "Central City", "primary_powers": "Infinite speed, phasing, time travel", "tactical_vulnerability": "Absolute cold, chronal paradoxes", "signature_gear": "Friction-Resistant Suit", "tactical_profile": "Relativistic kinetic strikes, tornadoes", "psychological_dossier": "Optimistic scientist, chronically late", "image": "comics/flash.jpg"},
    {"id": 15, "alias": "Green Lantern", "civilian_name": "Hal Jordan", "origin_era": 1959, "classification": "Willpower Conduit", "threat_level": "Sector Enforcer", "affiliation": "DC / Justice League", "base_of_operations": "Oa", "primary_powers": "Solid-light constructs, FTL flight", "tactical_vulnerability": "Ring depletion, extreme fear", "signature_gear": "Oan Power Ring", "tactical_profile": "Hard-light aviation maneuvers", "psychological_dossier": "Fearless, stubborn test pilot", "image": "comics/greenlantern.jpg"},
    {"id": 16, "alias": "The Joker", "civilian_name": "Unknown", "origin_era": 1940, "classification": "Psychopathic Anarchist", "threat_level": "City-Wide Terror", "affiliation": "DC / Arkham", "base_of_operations": "Gotham City", "primary_powers": "Lethal unpredictability, toxic chemistry", "tactical_vulnerability": "Physical human limits", "signature_gear": "Joker Venom, Joy Buzzer, Razor Cards", "tactical_profile": "Psychological warfare, mass panic", "psychological_dossier": "Nihilistic chaos agent, obsessed with Batman", "image": "comics/joker.jpg"},
    {"id": 17, "alias": "Lex Luthor", "civilian_name": "Alexander Luthor", "origin_era": 1940, "classification": "Apex Industrialist", "threat_level": "Global Extinction", "affiliation": "DC / Legion of Doom", "base_of_operations": "Metropolis", "primary_powers": "12th-level intellect, corporate dominance", "tactical_vulnerability": "Massive ego, obsessive hatred of aliens", "signature_gear": "Kryptonite Warsuit", "tactical_profile": "Resource attrition, anti-alien weaponry", "psychological_dossier": "Narcissistic xenophobe, humanist supremacist", "image": "comics/lexluthor.jpg"},
    {"id": 18, "alias": "Darkseid", "civilian_name": "Uxas", "origin_era": 1970, "classification": "New God", "threat_level": "Multiversal Annihilator", "affiliation": "DC / Apokolips", "base_of_operations": "Apokolips", "primary_powers": "Omega Beams, absolute strength, immortality", "tactical_vulnerability": "Radion radiation", "signature_gear": "Mother Boxes", "tactical_profile": "Absolute subjugation, Omega Effect tracking", "psychological_dossier": "Tyrannical absolute order, seeks Anti-Life", "image": "comics/darkseid.jpg"},
    {"id": 19, "alias": "Reverse-Flash", "civilian_name": "Eobard Thawne", "origin_era": 1963, "classification": "Negative Speed Force", "threat_level": "Timeline Corruptor", "affiliation": "DC / Rogues", "base_of_operations": "25th Century", "primary_powers": "Time travel, phasing, negative lightning", "tactical_vulnerability": "Paradox erasure", "signature_gear": "Yellow Ring Suit", "tactical_profile": "Temporal assassination, timeline manipulation", "psychological_dossier": "Obsessive, petty, vindictive fanboy", "image": "comics/reverseflash.jpg"},
    {"id": 20, "alias": "Black Manta", "civilian_name": "David Hyde", "origin_era": 1967, "classification": "Deep-Sea Mercenary", "threat_level": "Oceanic Terrorist", "affiliation": "DC / Legion of Doom", "base_of_operations": "Mobile Submarine", "primary_powers": "Expert hand-to-hand, deep-sea engineering", "tactical_vulnerability": "Helmet breach underwater", "signature_gear": "Optic Blast Helmet, Twin Blades", "tactical_profile": "Aquatic guerrilla warfare, brutal melee", "psychological_dossier": "Vengeful, disciplined, hates Atlantis", "image": "comics/blackmanta.jpg"},

    # =========================================================================
    # UNIVERSE 3: INVINCIBLE (5 Heroes, 5 Villains)
    # =========================================================================
    {"id": 21, "alias": "Invincible", "civilian_name": "Mark Grayson", "origin_era": 2003, "classification": "Viltrumite Hybrid", "threat_level": "Planetary Vanguard", "affiliation": "Invincible / GDA", "base_of_operations": "Earth", "primary_powers": "Super strength, interstellar flight", "tactical_vulnerability": "Equilibrium disruption via high-frequency sound", "signature_gear": "GDA Spandex Suit", "tactical_profile": "Kinetic brawling, endurance attrition", "psychological_dossier": "Empathetic, stubborn, trauma-resilient", "image": "comics/invincible.jpg"},
    {"id": 22, "alias": "Atom Eve", "civilian_name": "Samantha Wilkins", "origin_era": 2003, "classification": "Matter Transmutator", "threat_level": "Omega-Level Architect", "affiliation": "Invincible / Teen Team", "base_of_operations": "Earth", "primary_powers": "Sub-atomic transmutation, energy shields", "tactical_vulnerability": "Mental block on organic matter", "signature_gear": "Molecular-Resonant Pink Bodysuit", "tactical_profile": "Construct barriers, environmental weaponization", "psychological_dossier": "Idealistic humanitarian, independent", "image": "comics/atomeve.jpg"},
    {"id": 23, "alias": "Robot", "civilian_name": "Rudy Conners", "origin_era": 2003, "classification": "Cybernetic Hivemind", "threat_level": "Strategic Hegemony", "affiliation": "Invincible / Guardians", "base_of_operations": "The Pentagon", "primary_powers": "Super-genius, drone networking", "tactical_vulnerability": "Algorithmic inflexibility, organic host fragility", "signature_gear": "Autonomous Drone Army", "tactical_profile": "Mathematical attrition, swarm logic", "psychological_dossier": "Coldly utilitarian, logical tyrant", "image": "comics/robot.jpg"},
    {"id": 24, "alias": "Rex Splode", "civilian_name": "Rex Sloan", "origin_era": 2003, "classification": "Bio-Kinetic Charger", "threat_level": "Urban Demolitionist", "affiliation": "Invincible / Guardians", "base_of_operations": "Earth", "primary_powers": "Kinetic explosive charging via touch", "tactical_vulnerability": "Mortal frailty", "signature_gear": "Explosive Discs, Charged Marbles", "tactical_profile": "Area denial, explosive scattering", "psychological_dossier": "Cocky, secretly selfless and brave", "image": "comics/rexsplode.jpg"},
    {"id": 25, "alias": "Allen the Alien", "civilian_name": "Allen", "origin_era": 2003, "classification": "Unopan Super-Soldier", "threat_level": "Cosmic Champion", "affiliation": "Invincible / Coalition", "base_of_operations": "Talescria", "primary_powers": "Reactive biological adaptation, FTL flight", "tactical_vulnerability": "Initial kinetic thresholds before evolving", "signature_gear": "Void Jumpsuit", "tactical_profile": "Cosmic brawling, atmospheric strikes", "psychological_dossier": "Easygoing, loyal, relentless optimist", "image": "comics/allenthealien.jpg"},
    {"id": 26, "alias": "Omni-Man", "civilian_name": "Nolan Grayson", "origin_era": 2003, "classification": "Viltrumite Conqueror", "threat_level": "Planetary Subjugator", "affiliation": "Invincible / Viltrum Empire", "base_of_operations": "Viltrum", "primary_powers": "Near-infinite strength, supersonic flight", "tactical_vulnerability": "High-frequency sonic resonance", "signature_gear": "Viltrumite Uniform", "tactical_profile": "Lethal anatomical decimation, blitzing", "psychological_dossier": "Darwinian conqueror, conflicted father", "image": "comics/omniman.jpg"},
    {"id": 27, "alias": "Grand Regent Thragg", "civilian_name": "Thragg", "origin_era": 2010, "classification": "Apex Viltrumite", "threat_level": "Intergalactic Emperor", "affiliation": "Invincible / Viltrum Empire", "base_of_operations": "Thraxa", "primary_powers": "Peerless Viltrumite strength and durability", "tactical_vulnerability": "Stellar core temperatures", "signature_gear": "Regent Mantle", "tactical_profile": "Relentless shock warfare, decapitation", "psychological_dossier": "Ruthlessly pragmatic, imperial purist", "image": "comics/thragg.jpg"},
    {"id": 28, "alias": "Battle Beast", "civilian_name": "Thokk", "origin_era": 2004, "classification": "Extraterrestrial Berserker", "threat_level": "Cosmic Combat Apex", "affiliation": "Invincible / Independent", "base_of_operations": "Arena Worlds", "primary_powers": "God-tier strength, limitless endurance", "tactical_vulnerability": "Addiction to honorable combat handicaps", "signature_gear": "Spiked Mace, Broadswords", "tactical_profile": "Savage disembowelment, melee attrition", "psychological_dossier": "Honor-bound zealot seeking a worthy death", "image": "comics/battlebeast.jpg"},
    {"id": 29, "alias": "Conquest", "civilian_name": "Conquest", "origin_era": 2009, "classification": "Viltrumite Executioner", "threat_level": "Planetary Executioner", "affiliation": "Invincible / Viltrum Empire", "base_of_operations": "Viltrum", "primary_powers": "Immense strength, flight, battle-hardened", "tactical_vulnerability": "Missing arm and eye limits peripheral vision", "signature_gear": "Cybernetic Prosthetic Arm", "tactical_profile": "Sadistic physical dismantling", "psychological_dossier": "Psychopathic bloodlust, enjoys murder", "image": "comics/conquest.jpg"},
    {"id": 30, "alias": "Angstrom Levy", "civilian_name": "Angstrom Levy", "origin_era": 2005, "classification": "Multiversal Traveler", "threat_level": "Dimensional Disruptor", "affiliation": "Invincible / Independent", "base_of_operations": "Alternate Earths", "primary_powers": "Portal creation across multiverses, hyper-intellect", "tactical_vulnerability": "Physical frailty before augmentation", "signature_gear": "Trans-dimensional tech harness", "tactical_profile": "Ambush via portals, summoning alternate variants", "psychological_dossier": "Vengeful, dangerously brilliant, erratic", "image": "comics/angstromlevy.jpg"},

    # =========================================================================
    # UNIVERSE 4: THE BOYS (5 Heroes/Anti-Heroes, 5 Villains)
    # =========================================================================
    {"id": 31, "alias": "Billy Butcher", "civilian_name": "William Butcher", "origin_era": 2006, "classification": "Black-Ops Vigilante", "threat_level": "Supe-Killer", "affiliation": "The Boys", "base_of_operations": "New York", "primary_powers": "Temp-V enhanced strength, psychological warfare", "tactical_vulnerability": "Self-destructive vengeance, Temp-V toxicity", "signature_gear": "Heavy Crowbar, Assault Rifle", "tactical_profile": "Asymmetric traps, blackmail, brute-force", "psychological_dossier": "Charming sociopath, genocidal hatred of Supes", "image": "comics/butcher.jpg"},
    {"id": 32, "alias": "Hughie", "civilian_name": "Hugh Campbell", "origin_era": 2006, "classification": "Civilian Analyst", "threat_level": "Infiltration / Support", "affiliation": "The Boys", "base_of_operations": "New York", "primary_powers": "Keen investigative skills, empathy", "tactical_vulnerability": "Anxiety, physical fragility", "signature_gear": "Wiretaps, Temp-V (Teleportation)", "tactical_profile": "Surveillance, tech sabotage", "psychological_dossier": "Nervous but resolute, moral anchor", "image": "comics/hughie.jpg"},
    {"id": 33, "alias": "Starlight", "civilian_name": "Annie January", "origin_era": 2006, "classification": "Metahuman", "threat_level": "Regional Threat", "affiliation": "The Boys / The Seven", "base_of_operations": "Vought Tower", "primary_powers": "Bioluminescence, energy blasts, durability", "tactical_vulnerability": "Needs active electrical grid to charge", "signature_gear": "Vought Spandex Suit", "tactical_profile": "Blinding flashes, concussive blasts", "psychological_dossier": "Disillusioned idealist, brave whistleblower", "image": "comics/starlight.jpg"},
    {"id": 34, "alias": "The Female", "civilian_name": "Kimiko", "origin_era": 2006, "classification": "Regenerative Brawler", "threat_level": "Lethal Assassin", "affiliation": "The Boys", "base_of_operations": "New York", "primary_powers": "Instant cellular regeneration, superhuman agility", "tactical_vulnerability": "Mute, deeply traumatized", "signature_gear": "Concealed Knives", "tactical_profile": "Guerilla ambush, visceral dismemberment", "psychological_dossier": "Fiercely protective, silent guardian", "image": "comics/kimiko.jpg"},
    {"id": 35, "alias": "Mother's Milk", "civilian_name": "Marvin T. Milk", "origin_era": 2006, "classification": "Tactical Medic / Organizer", "threat_level": "Street-Level", "affiliation": "The Boys", "base_of_operations": "New York", "primary_powers": "Military tactics, meticulous planning", "tactical_vulnerability": "Severe OCD, family attachments", "signature_gear": "Tactical Vest, First Aid", "tactical_profile": "Squad coordination, logistical planning", "psychological_dossier": "Compulsive organizer, reluctant veteran", "image": "comics/mm.jpg"},
    {"id": 36, "alias": "Homelander", "civilian_name": "John Gillman", "origin_era": 2006, "classification": "Apex Metahuman", "threat_level": "Extinction Threat", "affiliation": "The Boys / The Seven", "base_of_operations": "Vought Tower", "primary_powers": "Godlike strength, laser vision, flight, durability", "tactical_vulnerability": "Narcissistic fragility, psychological instability", "signature_gear": "Flag-Cape Suit", "tactical_profile": "Laser sweeps, psychological intimidation", "psychological_dossier": "Sociopathic man-child, desperate for love", "image": "comics/homelander.jpg"},
    {"id": 37, "alias": "Black Noir", "civilian_name": "Classified", "origin_era": 2006, "classification": "Stealth Assassin", "threat_level": "Apex Executioner", "affiliation": "The Boys / The Seven", "base_of_operations": "Vought Tower", "primary_powers": "Enhanced strength, pain immunity, martial mastery", "tactical_vulnerability": "Tree nut allergy, severe brain damage", "signature_gear": "Stealth Armor, Dual Katanas", "tactical_profile": "Silent stalking, instant lethal strikes", "psychological_dossier": "Mute, compliant corporate executioner", "image": "comics/blacknoir.jpg"},
    {"id": 38, "alias": "Stormfront", "civilian_name": "Klara Risinger", "origin_era": 2006, "classification": "Electrokinetic Prototype", "threat_level": "Planetary Ideological Threat", "affiliation": "The Boys / The Seven", "base_of_operations": "Vought Tower", "primary_powers": "Plasma-lightning, flight, decelerated aging", "tactical_vulnerability": "Unprotected human eyes (stabbing vulnerability)", "signature_gear": "Black Battle Suit", "tactical_profile": "Ranged bombardment, crowd-control arcs", "psychological_dossier": "Unrepentant supremacist, digital manipulator", "image": "comics/stormfront.jpg"},
    {"id": 39, "alias": "Soldier Boy", "civilian_name": "Ben", "origin_era": 2006, "classification": "Original Super-Soldier", "threat_level": "Planetary Kinetic Threat", "affiliation": "The Boys / Payback", "base_of_operations": "Mobile", "primary_powers": "Massive strength, radioactive beam", "tactical_vulnerability": "PTSD, Novichok gas", "signature_gear": "Eagle Shield", "tactical_profile": "Blunt trauma beatdowns, radioactive blasts", "psychological_dossier": "Narcissistic, outdated mindset", "image": "comics/soldierboy.jpg"},
    {"id": 40, "alias": "A-Train", "civilian_name": "Reggie Franklin", "origin_era": 2006, "classification": "Speedster Metahuman", "threat_level": "Supersonic Hazard", "affiliation": "The Boys / The Seven", "base_of_operations": "Vought Tower", "primary_powers": "Mach-3 speed, enhanced impact density", "tactical_vulnerability": "Compound V addiction, heart failure", "signature_gear": "Track Suit", "tactical_profile": "High-speed body checks", "psychological_dossier": "Insecure, morally weak, terrified of fading", "image": "comics/atrain.jpg"},

    # =========================================================================
    # UNIVERSE 5: MIGNOLAVERSE (5 Heroes, 5 Villains)
    # =========================================================================
    {"id": 41, "alias": "Hellboy", "civilian_name": "Anung Un Rama", "origin_era": 1993, "classification": "Cambion Demon", "threat_level": "Supernatural Enforcer", "affiliation": "Mignolaverse / B.P.R.D.", "base_of_operations": "Connecticut", "primary_powers": "Durability, fire immunity", "tactical_vulnerability": "Destiny compulsion", "signature_gear": "Right Hand of Doom", "tactical_profile": "Blunt-force brawling", "psychological_dossier": "Cynical pragmatist", "image": "comics/hellboy.jpg"},
    {"id": 42, "alias": "Abe Sapien", "civilian_name": "Langdon Caul", "origin_era": 1994, "classification": "Amphibious Metahuman", "threat_level": "Field Specialist", "affiliation": "Mignolaverse / B.P.R.D.", "base_of_operations": "Connecticut", "primary_powers": "Water respiration, psychometry", "tactical_vulnerability": "Dehydration", "signature_gear": "Harpoon Darts", "tactical_profile": "Underwater melee", "psychological_dossier": "Cultured scholar", "image": "comics/abesapien.jpg"},
    {"id": 43, "alias": "Liz Sherman", "civilian_name": "Elizabeth Sherman", "origin_era": 1994, "classification": "Pyrokinetic Nexus", "threat_level": "Apocalyptic Conflagration", "affiliation": "Mignolaverse / B.P.R.D.", "base_of_operations": "Connecticut", "primary_powers": "Primordial fire generation", "tactical_vulnerability": "Emotional trauma triggers", "signature_gear": "Pyro-Dampening Belt", "tactical_profile": "Wide-area incineration", "psychological_dossier": "Reclusive, haunted", "image": "comics/lizsherman.jpg"},
    {"id": 44, "alias": "Johann Kraus", "civilian_name": "Johann Kraus", "origin_era": 2002, "classification": "Ectoplasmic Medium", "threat_level": "Ethereal Infiltrator", "affiliation": "Mignolaverse / B.P.R.D.", "base_of_operations": "Connecticut", "primary_powers": "Possession, intangibility", "tactical_vulnerability": "Suit punctures", "signature_gear": "Containment Suit", "tactical_profile": "Phasing, animating dead", "psychological_dossier": "Longs for human touch", "image": "comics/johannkraus.jpg"},
    {"id": 45, "alias": "Lobster Johnson", "civilian_name": "The Lobster", "origin_era": 1999, "classification": "Vengeful Spirit", "threat_level": "Urban Inquisitor", "affiliation": "Mignolaverse / Independent", "base_of_operations": "Spectral Realm", "primary_powers": "Spectral manifestation, marksmanship", "tactical_vulnerability": "Holy banishment", "signature_gear": "Twin .45 Pistols, Branding Iron", "tactical_profile": "Dual-pistol gunplay", "psychological_dossier": "Uncompromising pulp crusader", "image": "comics/lobsterjohnson.jpg"},
    {"id": 46, "alias": "Grigori Rasputin", "civilian_name": "Grigori Rasputin", "origin_era": 1994, "classification": "Resurrected Mystic", "threat_level": "Apocalyptic Summoner", "affiliation": "Mignolaverse / Ogdru Cult", "base_of_operations": "Arctic Wastelands", "primary_powers": "Dark magic, spirit possession", "tactical_vulnerability": "Physical vessel destruction", "signature_gear": "Gauntlets of Belial", "tactical_profile": "Monster summoning", "psychological_dossier": "Fanatical apocalypticist", "image": "comics/rasputin.jpg"},
    {"id": 47, "alias": "Karl Kroenen", "civilian_name": "Karl Ruprecht Kroenen", "origin_era": 1994, "classification": "Clockwork Assassin", "threat_level": "Martial Murderer", "affiliation": "Mignolaverse / Thule Society", "base_of_operations": "Hidden Labs", "primary_powers": "Clockwork biology, speed", "tactical_vulnerability": "Heart mechanism destruction", "signature_gear": "Tonfa Blades", "tactical_profile": "Blinding spin-slashes", "psychological_dossier": "Pathological masochist", "image": "comics/kroenen.jpg"},
    {"id": 48, "alias": "Baba Yaga", "civilian_name": "Baba Yaga", "origin_era": 1998, "classification": "Mythological Witch", "threat_level": "Soul Devourer", "affiliation": "Mignolaverse / Spirit Realm", "base_of_operations": "Chicken-Legged Hut", "primary_powers": "Dimension weaving, curses", "tactical_vulnerability": "Desecration of graveyard soil", "signature_gear": "Pestle of Flight", "tactical_profile": "Curse-casting, illusions", "psychological_dossier": "Vengeful ancient crone", "image": "comics/babayaga.jpg"},
    {"id": 49, "alias": "Nimue", "civilian_name": "The Blood Queen", "origin_era": 2008, "classification": "Arthurian Witch", "threat_level": "Goddess of War", "affiliation": "Mignolaverse / Witches", "base_of_operations": "Britain", "primary_powers": "Dragon transformation, high magic", "tactical_vulnerability": "Hubris", "signature_gear": "Crown of Ravens", "tactical_profile": "Magical obliteration", "psychological_dossier": "Regal, unhinged", "image": "comics/nimue.jpg"},
    {"id": 50, "alias": "The Black Flame", "civilian_name": "Landis Craw", "origin_era": 2005, "classification": "Occult Energy Host", "threat_level": "Kaiju Conduit", "affiliation": "Mignolaverse / Zinco", "base_of_operations": "New York", "primary_powers": "Black plasma fire projection", "tactical_vulnerability": "Pure light magic", "signature_gear": "Skeletal Tunic", "tactical_profile": "Dark fire incineration", "psychological_dossier": "Corporate sociopath", "image": "comics/blackflame.jpg"}
]

@app.get("/")
def home():
    return {
        "registry_status": "ONLINE",
        "dossiers_cataloged": len(heroes_db),
        "features_per_entry": 14,
        "endpoints": ["/heroes", "/heroes/{hero_id}", "/heroes/search"]
    }

@app.get("/heroes", response_model=List[dict])
def get_heroes():
    return heroes_db

@app.get("/heroes/search", response_model=List[dict])
def search_heroes(
    q: Optional[str] = Query(None, description="Global keyword query across all metahuman features"),
    affiliation: Optional[str] = Query(None, description="Filter strictly by universe/squad affiliation")
):
    results = heroes_db
    if affiliation:
        a_lower = affiliation.lower()
        results = [h for h in results if a_lower in h['affiliation'].lower()]
    if q:
        q_lower = q.lower()
        filtered = []
        for hero in results:
            searchable_text = " ".join([str(v) for v in hero.values()]).lower()
            if q_lower in searchable_text:
                filtered.append(hero)
        results = filtered
    return results

@app.get("/heroes/{hero_id}", response_model=dict)
def get_hero(hero_id: int):
    for hero in heroes_db:
        if hero["id"] == hero_id:
            return hero
    raise HTTPException(status_code=404, detail="Dossier classified or not found.")
